### ISSUE TITLE
Has anyone seen this error: "cut: only one type of list may be specified"

### ISSUE THREAD

**Issue by ryanbooker** [nix-community/nix-direnv#101]
I am trying to use nix-direnv in my nix setup on macOS to stop some local `nix-shell`s from being garbage collected.

I have it installed via `home-manager`, I have the settings in `/etc/nix/nix.conf` and I have a `.envrc` in each project that contains `use nix`.

I get the "cut" error mentions above, and the derivation isn't preserved when I garbage collect… :\

**Comment by Mic92** [comment]
I am not aware of nix-direnv using `cut`.
