### ISSUE TITLE
Error when nix-shell is an alias

### ISSUE THREAD

**Issue by SFrijters** [nix-community/nix-direnv#102]
After not touching some nix projects for a while and running nixpkgs updates regularly, the nix-direnv suddenly no longer functioned.

I think it is because my `nix-shell` command is aliased, and the lookup in `direnvrc` breaks on this.

```
$ command -v nix-shell
alias nix-shell='nix-shell --command "$(declare -p PS1); return"'

$ type -P nix-shell
/run/current-system/sw/bin/nix-shell

$ type --help
[...]
      -P	force a PATH search for each NAME, even if it is an alias,
    		builtin, or function, and returns the name of the disk file
    		that would be executed
[...]
```

This would be my suggested fix, I can open a PR for it if this seems like a good idea, but I don't know if I'm missing some subtlety here.

**Comment by SFrijters** [comment]
Ah, while I think the above is still a potential issue for people who use the `source_url` method of installation, I now read the docs more closely and I need to set the flakes override since I use unstable nix, so it's fixed for me.

Please let me know if they other issue is worth looking into.

**Comment by Mic92** [comment]
aliases in your own shell should not affect direnv or nix-direnv since your bashrc is not loaded in direnv. Your issue might have been related to something else.
