### ISSUE TITLE
How to revalidate cache for git+ssh

### ISSUE THREAD

**Issue by anilanar** [nix-community/nix-direnv#105]
I use flakes and try to use a private flake from my private github repo as such:

```
use flake git+ssh://git@github.com/anilanar/home.nix.git#shells.nix
```

However I have no clue how to revalidate the cache after I push something to the repo. In theory, I can use specific revisions but I don't want to do that if possible.

**Comment by Mic92** [comment]
I don't see any way but disabling caching.

**Comment by anilanar** [comment]
Well I guess I will use `use flake` with `flake.nix` and `flake.lock` and pay the price with some boilerplate.

So one either has to use specific commit ids with `use flake <git-url>` or use flake.nix + flake.lock otherwise updating is impossible.
