### ISSUE TITLE
Optionally move project-wise .direnv to a centralized location

### ISSUE THREAD

**Issue by yipengsun** [nix-community/nix-direnv#11]
Hi,

Currently, this `use_nix` function will create a `.direnv` folder along with the `.envrc` file. The problem is: I have some of my project stored in Dropbox, and this has 2 problems:

1. Dropbox will mess up symblinks
2. The `cache-` and `drv` files doesn't seem to be portable

Is it possible to add an additional environmental variable to store all `.direnv` in a centralized location?

**Comment by Mic92** [comment]
cc @zimbatm ?

**Comment by Mic92** [comment]
Would it work for you to use the exclude option? 

```
$ dropbox exclude add **.direnv
```

**Comment by zimbatm** [comment]
it's actually already possible but not documented enough: https://github.com/direnv/direnv/commit/faf5fc1c93453cafe1ab8bc8c7c3e8444599fc07

**Comment by yipengsun** [comment]
> Would it work for you to use the exclude option?
> 
> ```
> $ dropbox exclude add **.direnv
> ```

`dropbox` (or `dropbox-cli`) doesn't seem to be available on macOS (There's a `dbxcli` package, but that one doesn't have "excluding" capability). I'll try the `direnv_layout_dir` option.

**Comment by yipengsun** [comment]
I tried to add these lines to `$HOME/direnv/direnvrc`:
```
: ${XDG_CACHE_HOME:=$HOME/.cache}
pwd_hash=$(echo -n $PWD | shasum | cut -d ' ' -f 1)
direnv_layout_dir=$XDG_CACHE_HOME/direnv/layouts/$pwd_hash
```

And I created the `direnv` folder in `$HOME/.cache`. Still, no hashed folder is created. Actually, I think now `direnv` never caches anything.

**Comment by yipengsun** [comment]
BTW the `dropbox` tool does not handle wildcards if this [answer](https://superuser.com/questions/469776/how-to-exclude-files-not-folders-from-dropbox-sync) is true.

**Comment by Mic92** [comment]
Well. `nix-direnv` does not uses `direnv_layout_dir` yet.

**Comment by Mic92** [comment]
> BTW the `dropbox` tool does not handle wildcards if this [answer](https://superuser.com/questions/469776/how-to-exclude-files-not-folders-from-dropbox-sync) is true.

No but your shell should.

**Comment by yipengsun** [comment]
> > BTW the `dropbox` tool does not handle wildcards if this [answer](https://superuser.com/questions/469776/how-to-exclude-files-not-folders-from-dropbox-sync) is true.
> 
> No but your shell should.

Then each time there's a new `.direnv` folder, I have to re-run the command. I think it solves the problem on linux, but not optimally.

**Comment by Mic92** [comment]
Please check if https://github.com/nix-community/nix-direnv/pull/12 solves your problem.

**Comment by yipengsun** [comment]
Yes! The pull request solves my problem. Many thanks!

**Comment by Mic92** [comment]
It is also now documented here: https://github.com/nix-community/nix-direnv#storing-direnv-outside-the-project-directory

**Comment by yipengsun** [comment]
I think #12 breaks the prevent-garbage-collection feature:
https://github.com/nix-community/nix-direnv/blob/063d43483ec1bc51fa6906989ad298d906a9ba51/direnvrc#L82-L87
When I check `/nix/var/nix/gcroots/per-user/$(whoami)`, the `drv` link looks like this:
```
work-syp-researches-lhcb--data_analysis-lhcb--ntuples--gen -> /work/syp/researches/lhcb-data_analysis/lhcb-ntuples-gen//Users/syp/.cache/direnv/3f7e63a826736a47a12813a86ad10b4c4580f8c5/drv
```

And when I do a `nix-collect-garbage`, the cached nix-shell packages get deleted.

If I disable the `direnv_layout_dir`, then everything works fine.

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/nix-direnv/pull/15
