### ISSUE TITLE
Add substituters support

### ISSUE THREAD

**Issue by cab404** [nix-community/nix-direnv#112]
For some projects I need to configure substituters. 
`cachix use` is suboptimal due to not being pure (edits local nix.conf).

I propose adding something along the lines of
```
use nix-cache PATH
use nix-key PUBKEY
```
which would parse current system and environment substituters, add ones from command line opts, and collect them for later use in `use nix`

**Comment by Mic92** [comment]
You can do:

```
export NIX_CONF_DIR=$(pwd)/nix.conf
```

in your project and than set all the configuration you want inside this file.

A different hack is passing options like this:

```
use nix --builders ""
```

I am currently not interested in expanding the complexity of this project further given the alternative ways described above.

**Comment by katyo** [comment]
@Mic92 Seems hack doesn't works anymore:
```
direnv: using nix --pure --builders
error: '' is not a valid URL
```

**Comment by bbenne10** [comment]
[We don't special case `--builders` during argument parsing in `use_nix`](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L425), so it is assumed to be of single-argument form (i.e. take no additional options). I don't know what nix itself does, but you can try `--builders=""` in that case. No guarantees that it works, but if it doesn't we can modify the function in question to add support for it.

Personally, `NIX_CONF_DIR` feels more appropriate, but I understand some may not agree with me. If you'd like the argument parsed version, I'd happily accept a targeted patch that handles `--builders` in the same way `--attrs` is handled there and proves that it works reliably.
