### ISSUE TITLE
"path ... is not a flake" when using flake from outside the current repo

### ISSUE THREAD

**Issue by masonevans** [nix-community/nix-direnv#114]
Running `nix-darwin` using `nixpkgs-21.05-darwin` on Mac OS Catalina.  Shell is `fish`.

I am following the directions in the README to use a `flake.nix` from outside the current directory without needing to have a flake.nix in the current directory, however I always get the following error:

```
direnv: loading ~/Development/flake-pythonify/.envrc
direnv: using flake /Users/masonevans/Development/flake-python-test
error: path '/Users/masonevans/Development/flake-pythonify' is not a flake (because it doesn't contain a 'flake.nix' file)
```

I have the following setup

1.  A verified-working flake under `/Users/masonevans/Development/flake-python-test` which outputs a `devShell.x86_64-darwin` attribute.  Direnv works as expected in this directory and gives me a shell with my Python dev env.
2. A second directory (`/Users/masonevans/Development/flake-pythonify`) with `use flake /Users/masonevans/Development/flake-python-test` in `.envrc` (I've tried variations of that as well, e.g. `flake-python-test#devShell.x86_64-darwin`).  This directory gives me an error about a missing `flake.nix`.

My goal is to create a flake on my system that defines a Python dev environment which I can then reference from all my individual projects.  

My expectation, based on my reading of the README, is that I can define a flake in one place and then import it in multiple other directories, and this way I don't need to have a `flake.nix` in each project if I don't want to.

Output of `direnv status`

```
direnv status
direnv exec path /Users/masonevans/.nix-profile/bin/direnv
DIRENV_CONFIG /Users/masonevans/.config/direnv
bash_path /nix/store/cpgyi9khbv1yg2i22vg0zhmsnif9aih9-bash-4.4-p23/bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
Loaded RC path /Users/masonevans/Development/flake-pythonify/.envrc
Loaded watch: ".envrc" - 2021-09-21T10:54:31-06:00
Loaded watch: "../../.local/share/direnv/allow/333820b7d19679cefbbe829e9bd64414f5afc9306a0d09e082df328615e0abd3" - 2021-09-21T10:11:47-06:00
Loaded watch: "flake.nix" - 1969-12-31T17:00:00-07:00
Loaded watch: "flake.lock" - 1969-12-31T17:00:00-07:00
Loaded RC allowed false
Loaded RC allowPath
Found RC path /Users/masonevans/Development/flake-pythonify/.envrc
Found watch: ".envrc" - 2021-09-21T10:54:31-06:00
Found watch: "../../.local/share/direnv/allow/333820b7d19679cefbbe829e9bd64414f5afc9306a0d09e082df328615e0abd3" - 2021-09-21T10:11:47-06:00
Found RC allowed true
Found RC allowPath /Users/masonevans/.local/share/direnv/allow/333820b7d19679cefbbe829e9bd64414f5afc9306a0d09e082df328615e0abd3
```

**Comment by Mic92** [comment]
Does the following works for you?

```console
mkdir /tmp/{a,b}
cd /tmp/a
git init
nix flake init
git add flake.*
cd /tmp/b
echo 'use flake /tmp/a' > .envrc
direnv allow
```

**Comment by masonevans** [comment]
Nope, same error

```
~
➜  mkdir /tmp/{a,b}

~
➜  cd /tmp/a

/tmp/a
➜  git init
Initialized empty Git repository in /private/tmp/a/.git/

/tmp/a on  develop
➜  nix flake init

/tmp/a on  develop [!] took 2s
➜  git add flake.*

/tmp/a on  develop [+]
➜  cd /tmp/b

/tmp/b
➜  echo 'use flake /tmp/a' > .envrc
direnv: error /private/tmp/b/.envrc is blocked. Run `direnv allow` to approve its content

/tmp/b
➜  direnv allow
direnv: loading /private/tmp/b/.envrc
direnv: using flake /tmp/a
error: path '/private/tmp/b' is not a flake (because it doesn't contain a 'flake.nix' file)
error: path '/private/tmp/b' is not a flake (because it doesn't contain a 'flake.nix' file)
direnv: renewed cache
direnv: export ~XDG_DATA_DIRS

/tmp/b
➜
```

**Comment by Mic92** [comment]
Ah. It seems to me that you are not using nix-direnv 1.4, which introduced this feature:
https://github.com/nix-community/nix-direnv/releases/tag/1.4.0

**Comment by Mic92** [comment]
You can load it like this just before using `use flake ...`:
```
if ! has nix_direnv_version || ! nix_direnv_version 1.4.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/1.4.0/direnvrc" "sha256-cVSyO0/m0hbePv+plzua014InR0lNXa+0LTn0yEW0xc="
fi
```

**Comment by masonevans** [comment]
Thanks, yup, that solved the issue!

FWIW, I get a different hash than what you have in the example: `sha256-4XfVDjv75eHMWN4G725VW7BoOV4Vl3vAabK4YXIfPyE=`

**Comment by Mic92** [comment]
Right. I might have taken the hash using the wrong branch.
