### ISSUE TITLE
Document specifying another Nix file

### ISSUE THREAD

**Issue by sir4ur0n** [nix-community/nix-direnv#115]
If one wants to use a custom file (e.g. `shell-foo.nix`), it appears that `use nix shell-foo.nix` works.

What do you think about documenting this nice feature in the README?

Thank you for Nix-direnv :bow:

**Comment by Mic92** [comment]
Sounds good. Do you want to make a PR?

**Comment by sir4ur0n** [comment]
I proposed something in https://github.com/nix-community/nix-direnv/pull/116
