### ISSUE TITLE
error: 'print-dev-env' is not a recognised command

### ISSUE THREAD

**Issue by bbigras** [nix-community/nix-direnv#122]
My `.envrc` has `use flake`.

I wonder if it's related to the new nix release or because I removed `nix-direnv.enableFlakes` with home-manager. There was a message that it wasn't needed anymore.

Using `nix develop` directly is fine.

```
direnv: loading ~/dev/my_project/.envrc
direnv: using flake
error: 'print-dev-env' is not a recognised command
Try '/nix/store/n25kqxima1f2pacb1cygvg1a1ykxr0l8-nix-2.3.16/bin/nix --help' for more information.
error: 'flake' is not a recognised command
Try '/nix/store/n25kqxima1f2pacb1cygvg1a1ykxr0l8-nix-2.3.16/bin/nix --help' for more information.
direnv: renewed cache
direnv: export ~XDG_DATA_DIRS
```

**Comment by bbigras** [comment]
The problem is gone after updating nixos.

**Comment by mainrs** [comment]
Could you elaborate more? Ive updated my machine to the newest nix stable (21.11) and I get the same error.

**Comment by bradparker** [comment]
@mainrs The error is to with the Nix-direnv derivation using a version of Nix that doesn't include Flake support. In stable (21.11) the `nix` package is at version 2.3.16, which does not include Nix support, and that's what Nix-direnv will use by default:

https://github.com/NixOS/nixpkgs/blob/a7ecde854aee5c4c7cd6177f54a99d2c1ff28a31/pkgs/tools/misc/nix-direnv/default.nix#L5

In the unstable channel Nix is at version 2.4 so will include Flakes support.

Now, you may be able to get `nix-direnv` to use a newer nix with something like:

```nix
  nixpkgs.config = {
    packageOverrides = pkgs: {
      nix-direnv = pkgs.nix-direnv.override {
        nix = pkgs.nixUnstable;
      };
    };
  };
```

In your `configuration.nix`, but I'm not able to test that right now.

**Comment by brendanzab** [comment]
Hmm, seems like the `nix` argument was [only added recently](https://github.com/NixOS/nixpkgs/pull/145236), and is not available in my version of `nix-direnv` yet:

```
error: anonymous function at /nix/store/gyv64x5vz0y27vykrbz8xy9ad5hwffpk-source/pkgs/tools/misc/nix-direnv/default.nix:1:1 called with unexpected argument 'nix'

       at /nix/store/gyv64x5vz0y27vykrbz8xy9ad5hwffpk-source/lib/customisation.nix:69:16:

           68|     let
           69|       result = f origArgs;
             |                ^
           70|
(use '--show-trace' to show detailed location information)
```

I tried using `enableFlakes = true;`, but I still get the same error. 🤔

**Comment by brendanzab** [comment]
My current work-around is just to use:
```
# reload when these files change
watch_file flake.nix
watch_file flake.lock
# load the flake devShell
eval "$(nix print-dev-env)"
```
in my `.envrc`s.

**Comment by brendanzab** [comment]
Ohhh! It seems `programs.direnv.nix-direnv.enableFlakes` was added _back_ to into home manager in https://github.com/nix-community/home-manager/pull/2520! So yeah, this works for me now:

```nix
programs.direnv = {
    enable = true;

    nix-direnv = {
      enable = true;
      enableFlakes = true;
    };
};
```

**Comment by mainrs** [comment]
> Ohhh! It seems `programs.direnv.nix-direnv.enableFlakes` was added _back_ to into home manager in [nix-community/home-manager#2520](https://github.com/nix-community/home-manager/pull/2520)! So yeah, this works for me now:
> 
> ```nix
> {
>   programs.direnv = {
>     enable = true;
> 
>     nix-direnv = {
>       enable = true;
>       enableFlakes = true;
>     };
>   };
> }
> ```

Didn't they remove it in the first place since flake support was always enabled by default? D: It's on master only, right?

**Comment by bradparker** [comment]
Ohhh, this …

> I tried using enableFlakes = true;, but I still get the same error. 🤔

… plus this …

> Ohhh! It seems programs.direnv.nix-direnv.enableFlakes was added back to into home manager in nix-community/home-manager#2520!

Makes a lot of sense. I guess the home manager config was overriding the override and setting `enableFlkaes` to the default for home manager (which I’d assume is `false`).

> So yeah, this works for me now:
> 
> {
>   programs.direnv = {
>     enable = true;
> 
>     nix-direnv = {
>       enable = true;
>       enableFlakes = true;
>     };
>   };
> }

Awesome! Thanks!

**Comment by Mic92** [comment]
> > Ohhh! It seems `programs.direnv.nix-direnv.enableFlakes` was added _back_ to into home manager in [nix-community/home-manager#2520](https://github.com/nix-community/home-manager/pull/2520)! So yeah, this works for me now:
> > ```nix
> > {
> >   programs.direnv = {
> >     enable = true;
> > 
> >     nix-direnv = {
> >       enable = true;
> >       enableFlakes = true;
> >     };
> >   };
> > }
> > ```
> 
> Didn't they remove it in the first place since flake support was always enabled by default? D: It's on master only, right?

Yes. Reverting nixFlakes again from 21.11 created a lot of chaos.
