### ISSUE TITLE
Flake: wrong cached shell used

### ISSUE THREAD

**Issue by archseer** [nix-community/nix-direnv#126]
After the release of nix 2.4 with flake support, I had to remove `programs.direnv.nix-direnv.enableFlakes` from my config since flakes are now always enabled: ''.../users/profiles/direnv' no longer has any effect; please remove it."

But now entering a directory that uses direnv+flakes uses the wrong environment, and I have to manually `touch flake.lock` or `direnv reload` to get the right shell.

https://asciinema.org/a/UVJsGokXgMzSveo6aC1MtrTO4

I've tried removing `.direnv` and clearing the cache.

**Comment by archseer** [comment]
Note that my `flake-profile` in `.direnv` also doesn't seem to appear in `/nix/var/nix/gcroots/auto`, and and invalid symlink appears there instead.

**Comment by archseer** [comment]
Seems to be https://github.com/numtide/devshell/issues/149

**Comment by Congee** [comment]
Might reopen to keep track of this issue? Upstream says https://github.com/nix-community/nix-direnv/issues/109 is the cause

**Comment by Mic92** [comment]
If #109 is fixed, this issue is fixed as well. So this is fine.
