### ISSUE TITLE
Reference to $NIX_BUILD_TOP in `use_flake` fails if shellHook unsets it

### ISSUE THREAD

**Issue by lilyball** [nix-community/nix-direnv#128]
If my `shellHook` unsets the `NIX_BUILD_TOP` env var, there's an unguarded reference to it in the `use_flake` function that will then fail.

https://github.com/nix-community/nix-direnv/blob/69bec056fb036ff526184a995f07ee7b3f0abf0b/direnvrc#L171

This results in an error

```
/nix/store/77rjgliqwa9qp2hk1nwaic0n75l01pi2-nix-direnv-1.5.0/share/nix-direnv/direnvrc:171: NIX_BUILD_TOP: unbound variable
```

#125 rewrites a lot of this code but it still has this unguarded access to `$NIX_BUILD_TOP`.

In general, nix-direnv should assume that evaluating `$profile_rc` may make arbitrary changes to the environment and so it can't rely on any env var still existing at this point.

---

This was discovered when trying to use [numtide/devshell](https://github.com/numtide/devshell). I know there's an incompatibility right now with cached runs (see https://github.com/nix-community/nix-direnv/issues/109) but it should still work on a `direnv reload` at least

**Comment by Mic92** [comment]
Ok. Noted. Since I now work with zimbatm closer together, I hope to tackle this eventually. Otherwise I would also accept pull requests.

**Comment by lilyball** [comment]
@Mic92 Any chance of getting a new release with this fix? Also updating nixpkgs too, since that currently has 2.1.0.

**Comment by bbenne10** [comment]
i can cut a release this coming weekend if no one else is available
