### ISSUE TITLE
1.5.0 release has wrong version set

### ISSUE THREAD

**Issue by LunNova** [nix-community/nix-direnv#133]
The 1.5.0 tag has the version in direnvrc set to 1.4.0 so `if ! has nix_direnv_version || ! nix_direnv_version 1.5.0; then` will update even if it's already loaded.

https://github.com/nix-community/nix-direnv/blob/d26fc52f8d22540b6bc837120e9c4db7fdec3a4d/direnvrc#L7

**Comment by Mic92** [comment]
fix in https://github.com/nix-community/nix-direnv/blob/1.5.1/direnvrc
