### ISSUE TITLE
DOCS: make it clear whether it is appropriate to track the contents of the .direnv directory with `git`

### ISSUE THREAD

**Issue by hab25** [nix-community/nix-direnv#138]
It isn't obvious to me because there is conflicting evidence:

Evidence that makes one think it should be tracked:
- `.direnv` is created in the project directory by default.
- The tool does not touch the project's `.gitignore`. Neither the tool nor the documentation suggest modifying `.gitignore`.
- Having a shared cache could save some development time. 

Evidence that makes one think it should NOT be tracked:
- The files make references to OS/architecture (e.g. `export $'NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu'=1;`) and the nix store (e.g. `export $'out'=$'/nix/store/dj0qni0mardvd6mjr5a57ajayfpkfsa4-nix-shell'`). This makes one think that this cache could cause problems for others that differ in at least one of these aspects.
- [This documentation section](https://github.com/nix-community/nix-direnv#storing-direnv-outside-the-project-directory) suggests some problems. Aren't remote `git` repositories technically also backups?

**Comment by Mic92** [comment]
To reduce friction I would actually suggest users to put `.direnv` in their global ~/.gitignore.
https://github.com/Mic92/dotfiles/blob/351ff0915b025a8c31163726591359ca22d7eb9e/.gitignore#L8
I could be still added on a project base, but not every project has .envrc upstream especially in the context of nix.

**Comment by bbenne10** [comment]
I use the linked documentation section and don't track `.direnv` at all.
The whole point is that these environment are fully reproducible, so reproducing them is what we should do. 

I think the documentation section doesn't strongly enough make a case for why it is there (even if it is useful!) or make a stance either way on the tracking of `.direnv`. I'll leave this open until I can get around to updating the docs to reflect the stance outlined here.
