### ISSUE TITLE
Cut release for 1.6.0

### ISSUE THREAD

**Issue by bbenne10** [nix-community/nix-direnv#139]
With the last merge, we're able to use nix-direnv very well for some internal development tasks. Yay! However, I now have to explain to developers that they need at least `direnv` 2.21.3 (because `nix-direnv` assumes `shopt -s extglob` has been run, which was changed in direnv at that point release) and `nix-direnv` at `HEAD`.

It's not entirely clear from reading the documentation which version you'll get for all of the installations as of today (the nix ones get 1.5.1, but installing from source gets latest and greatest features, for instance). 

This would all be greatly simplified if:

* `nix-direnv` declared a minimum version of direnv by calling `direnv_version 2.21.3` (or later if there's some other feature I have missed that `nix-direnv` requires)
* There was a release with the latest features (namely allowing arguments to be passed to the flake invocation). I recommend 1.6.0, as this is a new feature rather than a bugfix. But 1.5.2 or 2.0.0 would be fine too. 

I'm happy to open a PR for the former, but I'm not sure I'm qualified to do the work for the latter. Please let me know what you'd prefer.

**Comment by Mic92** [comment]
Can you do the pr for `direnv_version`. I will create a release afterwards.

**Comment by bbenne10** [comment]
With the merge of #141, is there anything standing in the way of cutting a release?

**Comment by Mic92** [comment]
done in https://github.com/nix-community/nix-direnv/releases/tag/1.6.0

**Comment by bbenne10** [comment]
Thank you! This will help us quite a bit.

**Comment by Mic92** [comment]
btw using 

```
if ! has nix_direnv_version || ! nix_direnv_version 1.6.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/1.6.0/direnvrc" "sha256-FqqbUyxL8MZdXe5LkMgtNo95raZFbegFpl5k2+PrCow="
fi
```

you can also download from your fork

**Comment by bbenne10** [comment]
We have some internal reasons why we didn't want to handle this that way, but we considered it. :)
