### ISSUE TITLE
Upgrade flake dependencies (to support `outputs.devShells`)

### ISSUE THREAD

**Issue by VojtechStep** [nix-community/nix-direnv#142]
According to the commit log, the current flake inputs were locked some 8 months ago.

The pinned version of nixpkgs provides some pre-release version of 2.4, but there were various improvements since then.

The newer version of the nix CLI supports getting development environment from `outputs.devShells`, while the old one only searches for exposed packages, e.g. when having `use flake .#hw06` in my .envrc:
```
error: flake 'git+file:<flake-path>' does not provide attribute 'packages.x86_64-linux.hw06', 'legacyPackages.x86_64-linux.hw06' or 'hw06'
```

The flake itself looks like this:
```
git+file:<flake-path>
└───devShells
    └───x86_64-linux
        └───hw06: development environment 'nix-shell'
```

A workaround is to either set `inputs.nix-direnv.inputs.nixpkgs.follows = "nixpkgs"` when using nix-direnv as a flake (unlikely), or install it with `nix profile install --recreate-lock-file --no-write-lock-file github:nix-community/nix-direnv`, which ignores the lockfile.

**Comment by bbenne10** [comment]
Is the recent update to flake.lock and the release of 2.0 enough to handle this case? I have yet to test, but I figure asking might be quicker and more useful.

**Comment by bbenne10** [comment]
Thank you for the quick response. Closing, as there's nothing to do :)
