### ISSUE TITLE
nix-direnv doesn't support nesting environments?

### ISSUE THREAD

**Issue by Narice** [nix-community/nix-direnv#143]
When having multiple layers of direnv, the shell only takes into account the last layer.
For example, if I have a folder requiring a latex install, and a subfolder in it requiring python, when entering the python folder, I lose the latex install.

**Comment by Mic92** [comment]
I think this is rather a "feature" of direnv in how it handles nesting rather than in the power of nix-direnv. I think it purposefully clears out environment variables.

But you can use

```
source_env ..
```

from your nested .envrc to load it's parent back.

cc @zimbatm

**Comment by zimbatm** [comment]
That's right. Use `source_env ..` or `source_up` to load the parent environment.
