### ISSUE TITLE
Build-unrelated cached varaibles cause weird issues

### ISSUE THREAD

**Issue by allgreed** [nix-community/nix-direnv#144]
I've spent quite some time debugging what essentially was mis-cached (is that a word?] `DISPLAY` variable.

I cannot think of a sensible use case where caching the `DISPLAY` directly by `nix-direnv` would make sense (but I can be wrong).
There may be more variables that shouldn't be cached, but it's probably better to deal with it on a var by var basis.

Obviously rebuilding the env is a perfect workaround.

**Comment by bbenne10** [comment]
Would you mind testing the just released 2.0 release? We've drastically updated the way variables are cached. I can't promise it's better, but it may help.
