### ISSUE TITLE
flake: support --system flag?

### ISSUE THREAD

**Issue by arianvp** [nix-community/nix-direnv#146]
```
use flake --system x86_64-darwin
```

gives me
```
direnv: using flake --system x86_64-darwin
error: flag '--system' requires 1 argument(s)
Try '/nix/var/nix/profiles/default/bin/nix --help' for more information.
error: flag '--system' requires 1 argument(s)
Try '/nix/var/nix/profiles/default/bin/nix --help' for more information.
direnv: renewed cache
direnv: export +XDG_DATA_DIRS
```

whilst this works with `use nix`

**Comment by Mic92** [comment]
Are you on nix-direnv 1.6? It includes https://github.com/nix-community/nix-direnv/pull/136

**Comment by bbenne10** [comment]
This is explicitly what #136 is for. If you're not yet on 1.6.0, please upgrade. 

This functionality should work exactly as expected, but you need to include an explicit path, as we use that argument to track the flake expression in use:

```use flake . --system x86_64-darwin```

**Comment by arianvp** [comment]
Works!
