### ISSUE TITLE
Add to nixpkgs?

### ISSUE THREAD

**Issue by DamienCassou** [nix-community/nix-direnv#16]
Is it possible to add this project to [nixpkgs](https://github.com/NixOS/nixpkgs)?

**Comment by Mic92** [comment]
Yes.

**Comment by DamienCassou** [comment]
I have started [working on it](https://github.com/DamienCassou/nixpkgs/commit/c8b4d950ee46da65bd4077e18bd4b5ff2cca0f28). The obvious question is how to make direnv find nix-direnv: we don't want to ask the user to write `source /nix/store/...nix-direnv/...` in their `direnvrc`.

I thought about creating a `direnvWithPlugins` derivation. Is this the way to go?

**Comment by Mic92** [comment]
@DamienCassou until we have a solution in https://github.com/nix-community/nix-direnv/issues/5
I would suggest to let user install it into their profile and than add to
direnvrc.

```bash
if [ -f "$HOME/.nix-profile/share/nix-direnv/direnvrc" ]; then
  source "$HOME/.nix-profile/share/nix-direnv/direnvrc"
fi
```

Alternatively they could also inline in homemanager it into their direnvrc:

```bash
source ${pkgs.direnvrc}/share/nix-direnv/direnvrc
```

**Comment by Mic92** [comment]
Note that nix flakes will deprecate my usage of this plugin. See https://zimbatm.com/NixFlakes/#direnv-integration

**Comment by Mic92** [comment]
nix flakes will be a lot faster.

**Comment by DamienCassou** [comment]
Should I open a PR with my branch then?

**Comment by DamienCassou** [comment]
Done: https://github.com/NixOS/nixpkgs/pull/87475.

**Comment by Mic92** [comment]
Merged and also updated the installation instructions: https://github.com/nix-community/nix-direnv
