### ISSUE TITLE
Automate release management upstream to nixpkgs

### ISSUE THREAD

**Issue by bbenne10** [nix-community/nix-direnv#175]
Since doing something hard should be done more often, I think we ought to automate submission of (or generation of the sha256 for submission of) `nix-direnv` into `nixpkgs`. I'm not sure exactly how to do this (`nix-prefetch-github` looks maybe okay?)

@mdarocha: Would you mind describing how you prepped tghe release for 2.0.1?

**Comment by mdarocha** [comment]
When bumping releases, I followed the contributing guide in the nixpkgs manual.

I just bumped the version tag, and deleted the sha256. After a rebuild, nix gave me a new sha256 to input.

If you're looking into automating nixpkgs updates, you should look into https://github.com/ryantm/nixpkgs-update

**Comment by bbenne10** [comment]
I was aware of the contributing guide. I was hoping you had a slightly better method of fetching the sha256, but it looks like nixpkgs-update might solve that issue somewhat. Thank you. I'll work on integrating this.

**Comment by Mic92** [comment]
https://github.com/Mic92/nix-update/ might also work

**Comment by bbenne10** [comment]
Since these all require checkouts of `nixpkgs` locally, I don't think that there's much to do other than pick one and integrate it into a release workflow. I might be able to script it a bit, but not much will change there overall. Thanks. I think I'm closing this.
