### ISSUE TITLE
Broken symlink created in `.direnv` with `use_flake`

### ISSUE THREAD

**Issue by duckpuppy** [nix-community/nix-direnv#177]
If I use `use_flake` in my `.envrc`, I get a broken symlink in my `.direnv` directory.

It looks like this snippet of code is the problem:

https://github.com/nix-community/nix-direnv/blob/8a731ae0abedf0ebbb360e225f81e543bc16ca24/direnvrc#L194-L199

If I'm reading that right:

- Line 195: sets `drv` to the real path of `tmp_profile`
- Line 198: REMOVES `tmp_profile` (so now it definitely doesn't exist)
- Line 199: uses `_nix_add_gcroot` to create a symlink to the now non-existent `tmp_profile` via the `drv` variable.

This seems guaranteed to create a broken link...

Is there a reason that symlink to nowhere is needed?

**Comment by duckpuppy** [comment]
Contents of an example `.direnv`:
```
$ ls -l .direnv
total 4.0K
   0 drwxr-xr-x 8 paikens staff  256 May  3 11:13 flake-inputs
   0 lrwxr-xr-x 1 paikens staff   78 May  3 11:13 flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa -> /Users/paikens/src/work/use_flake_test/.direnv/flake-profile.78954
4.0K -rw-r--r-- 1 paikens staff 1.8K May  3 11:13 flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc
```

`/Users/paikens/src/work/use_flake_test/.direnv/flake-profile.78954` doesn't exist, and is the value of `$drv` for this project.

**Comment by bbenne10** [comment]
@Mic92: Do you have  any ideas on this? It does seem useless, but the line itself seems to go back as far as our `use_flake` implementation does so I'm not sure I can speak to what the purpose is.

**Comment by Mic92** [comment]
> If I use `use_flake` in my `.envrc`, I get a broken symlink in my `.direnv` directory.
> 
> It looks like this snippet of code is the problem:
> 
> https://github.com/nix-community/nix-direnv/blob/8a731ae0abedf0ebbb360e225f81e543bc16ca24/direnvrc#L194-L199
> 
> If I'm reading that right:
> 
>     * Line 195: sets `drv` to the real path of `tmp_profile`

tmp_profile is a symlink to the nix store, `realpath` resolves this link. So `drv` will actually contains a store path not tmp_profile.
It seems to be not a symlink in your case. I don't know why. Can you delete `.direnv` and see if the issue reproduces after re-entering the project?

> 
>     * Line 198: REMOVES `tmp_profile` (so now it definitely doesn't exist)

Right, it was just a symlink so this is fine.

> 
>     * Line 199: uses `_nix_add_gcroot` to create a symlink to the now non-existent `tmp_profile` via the `drv` variable.

Again, at this point it should point to the nix store and not tmp_profile because we resolved a symlink in the first place.

> 
> 
> This seems guaranteed to create a broken link...
> 
> Is there a reason that symlink to nowhere is needed?


This is what it usually looks like:

```
╭─[~/.homesick/repos/dotfiles]─[master*]
╰─ % ls -la .direnv/
drwxr-xr-x   - joerg  4 May 08:30  flake-inputs/
lrwxrwxrwx  57 joerg  4 May 08:30  flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa -> /nix/store/wpdg6jh7glr5ps3jicfg6xfcpnbzy5gj-nix-shell-env
.rw-r--r-- 56k joerg  4 May 08:30  flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc
```

There is also a unit test that verify this. Is the unittest working for you? https://github.com/nix-community/nix-direnv/blob/master/tests/test.py#L97
This is the version I tested it with:

```
 if ! has nix_direnv_version || ! nix_direnv_version 2.1.0; then
   source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.1.0/direnvrc" "sha256-FAT2R9yYvVg516v3LiogjIc8YfsbWbMM/itqWsm5xTA="
 fi
```

**Comment by duckpuppy** [comment]
https://github.com/nix-community/nix-direnv/blob/8a731ae0abedf0ebbb360e225f81e543bc16ca24/direnvrc#L188

This resolves to the .direnv directory (layout_dir) appended with `flake-profile.<process_id>`.

**Comment by duckpuppy** [comment]
As far as I've been able to debug - that file (the one pointed to by tmp_profile) never actually exists at all.

**Comment by duckpuppy** [comment]
I ran the unit tests - and it results in a broken symlink.

```
$ python tests/test.py
EE
======================================================================
ERROR: setUpClass (__main__.FlakeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paikens/src/personal/nix-direnv/tests/test.py", line 41, in setUpClass
    shutil.copytree(TEST_ROOT.joinpath("testenv"), cls.testenv)
  File "/nix/store/4wqbim64yg4yr4a5wl50hf11ghhdqmz4-python3-3.9.12/lib/python3.9/shutil.py", line 566, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/nix/store/4wqbim64yg4yr4a5wl50hf11ghhdqmz4-python3-3.9.12/lib/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/paikens/src/personal/nix-direnv/tests/testenv/.direnv/nix-profile-pre373314.6766fb6503a', '/tmp/tmp66oukg9s/testenv/.direnv/nix-profile-pre373314.6766fb6503a', "[Errno 2] No such file or directory: '/Users/paikens/src/personal/nix-direnv/tests/testenv/.direnv/nix-profile-pre373314.6766fb6503a'")]

======================================================================
ERROR: setUpClass (__main__.NixShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/paikens/src/personal/nix-direnv/tests/test.py", line 41, in setUpClass
    shutil.copytree(TEST_ROOT.joinpath("testenv"), cls.testenv)
  File "/nix/store/4wqbim64yg4yr4a5wl50hf11ghhdqmz4-python3-3.9.12/lib/python3.9/shutil.py", line 566, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/nix/store/4wqbim64yg4yr4a5wl50hf11ghhdqmz4-python3-3.9.12/lib/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/paikens/src/personal/nix-direnv/tests/testenv/.direnv/nix-profile-pre373314.6766fb6503a', '/tmp/tmpxvg382_b/testenv/.direnv/nix-profile-pre373314.6766fb6503a', "[Errno 2] No such file or directory: '/Users/paikens/src/personal/nix-direnv/tests/testenv/.direnv/nix-profile-pre373314.6766fb6503a'")]

----------------------------------------------------------------------
Ran 0 tests in 0.009s

FAILED (errors=2)
$ ls -l tests/testenv/.direnv
total 52K
  0 lrwxr-xr-x 1 paikens staff  79 May  4 09:42 nix-profile-pre373314.6766fb6503a -> /Users/paikens/src/personal/nix-direnv/tests/testenv/.direnv/flake-profile.5283
52K -rw-r--r-- 1 paikens staff 52K May  4 09:42 nix-profile-pre373314.6766fb6503a.rc
```

I ran that from a nix-shell in the cloned repo, and I also entered `tests/testenv` and ran `direnv allow`.

**Comment by bbenne10** [comment]
Is there any other symptom other than a broken symlink?

It looks as if you're using macOS (based upon your `$HOME` path).
Can you share how your nix store is set up?

**Comment by duckpuppy** [comment]
I assume the lack of GC protection on the flake derivation without a gcroot reference. I did stumble on this problem because of a misbehaving VSCode plugin (it scans the workspace on startup and chokes when it hits the broken link), so it did cause a problem in my case outside of Nix.

I am on macOS. Nix is installed as a multi-user install. What other details do you need? I'll provide whatever info helps. I was wondering if zsh being the default shell for macOS was part of the problem (though I use zsh on all systems I touch... I'll test on a Linux system I have to see if this problem exists there too).

```
$ nix --version
nix (Nix) 2.4
```

**Comment by duckpuppy** [comment]
What I don't see is how tmp_profile points to a path in the nix store - I can't see where that would be the case given how it's declared in the function.

**Comment by bbenne10** [comment]
https://github.com/nix-community/nix-direnv/blob/8a731ae0abedf0ebbb360e225f81e543bc16ca24/direnvrc#L188-L192

These lines, which are admittedly a bit dense, assign `tmp_profile` to a path we desire and then use it during a `nix print-dev-env` invocation as the `--profile` argument (which should cause `tmp_profile` to end up as a symlink to the nix store).

I am also using macOS and this is working fine for me. I wonder if it has to do with the fact that I'm using `nixUnstable` locally (nix 2.5pre, though I should update).

zsh doesn't play into this - we *always* execute with bash due to the way direnv iteself invokes a shell. (It's a long shot since this doesn't do anything fancy bash-wise, but I *do* wonder if it has to do with the fact that the shipped bash version on macOS being VERY out of date. Do you have any other bash version installed? Or is `/bin/bash` the only bash you have?)

What version of macOS? How is your nix store set up? (can we get the output of `mount`, maybe? I'm wondering if it has to do with filesystems and how they handle symlinks)

**Comment by duckpuppy** [comment]
Actually... I take back part of that. I've had a wipe and reinstall of the OS since I first installed Nix, so the nix share SHOULD be created by the install script.

**Comment by duckpuppy** [comment]
OK, `$NIX_BIN_PREFIX` points to a different version of nix than what's on my path... `nix (Nix) 2.8.0`. Using that directly in the `print-dev-env` command still works when ran directly, though.

**Comment by duckpuppy** [comment]
I checked my Linux machine and interestingly, I have the same problem there. BUT, also interestingly, it seems it worked in the past.

I have a long running project with a shell.nix (not a flake), so it's using `use nix` in the .envrc. It's a project where I was working through code examples from Mastering Typescript.

```
$ ls -l .direnv
total 92K
8.0K -rw-r--r-- 1 duckpuppy duckpuppy 6.3K Jan 26 09:37 cache-pre348193.a3d847c3bd3
8.0K -rw-r--r-- 1 duckpuppy duckpuppy 6.3K Feb  7 10:19 cache-pre349555.83ab260bbe7
8.0K -rw-r--r-- 1 duckpuppy duckpuppy 6.3K Feb 16 15:07 cache-pre352151.18a062b02d6
8.0K -rw-r--r-- 1 duckpuppy duckpuppy 6.6K Feb 16 16:26 cache-pre355100.19574af0af3
   0 lrwxrwxrwx 1 duckpuppy duckpuppy   57 Feb 16 16:26 drv -> /nix/store/69y8qp3r0afgiqcp9ziyya3f9a82m73b-nix-shell.drv
4.0K lrwxrwxrwx 1 duckpuppy duckpuppy   70 May  4 13:59 nix-profile-pre373314.6766fb6503a -> /home/duckpuppy/src/mastering-typescript/.direnv/flake-profile.2195095
 56K -rw-r--r-- 1 duckpuppy duckpuppy  53K May  4 13:59 nix-profile-pre373314.6766fb6503a.rc
```

The interesting bit is that it WORKED in Feb. That's a valid symlink. The one from today is broken.

**Comment by duckpuppy** [comment]
I figured it out. Through a weird and long to explain bit of hackery, the `realpath` command was being overridden by a long-dormant function also called `realpath` in my direnvrc. That's why it worked in Feb - that was before this commit: https://github.com/nix-community/nix-direnv/commit/deb345be8224751db93cbb86c597ab81f3b5d44d
