### ISSUE TITLE
caching for custom functions

### ISSUE THREAD

**Issue by jaybutera** [nix-community/nix-direnv#178]
I'm using a single nix flake in multiple different directories so I wrote a function in `~/.config/direnv/lib/use_flake.sh`. And just call `use pythonflake` in the envrc files.

```
use_pythonflake() {
   watch_file ~/.dotfiles/envs/python/flake.nix
   watch_file ~/.dotfiles/envs/python/flake.lock
   eval "$(nix print-dev-env --profile "$(direnv_layout_dir)/flake-profile" ~/.dotfiles/envs/python)"
}
```

However the flakes are being garbage collected again. I'm not sure how exactly direnv roots are tracked by the garbage collector but it would be great if I could cache these custom functions.

**Comment by Mic92** [comment]
I think you can get a gcroot doing this:

```
$ nix print-dev-env --profile /nix/var/nix/gcroots/per-user/$USER/my-env
```

But make sure you have this enabled: https://github.com/nix-community/nix-direnv#via-configurationnix-in-nixos

**Comment by bbenne10** [comment]
@jaybutera: Is this resolved?

**Comment by jaybutera** [comment]
I changed the third line to

```eval "$(nix print-dev-env --profile /nix/var/nix/gcroots/per-user/$USER/python-flake ~/.dotfiles/envs/python)"```

But it is still getting garbage collected. I see the gc root at `/nix/var/nix/gcroots/per-user/casper/python-flake` which links to `/nix/store/34zmsfwga1l7z6zxq0b5v3359lb4jamy-nix-shell-env`.

**Comment by jaybutera** [comment]
Sorry correction, the store file is not being garbage collected but it is still re-downloading the nix flake dependencies once a day.

This is the whole function:

```
use_pythonflake() {
  watch_file ~/.dotfiles/envs/python/flake.nix
  watch_file ~/.dotfiles/envs/python/flake.lock
  eval "$(nix print-dev-env --profile /nix/var/nix/gcroots/per-user/$USER/python-flake ~/.dotfiles/envs/python)"
}
```

**Comment by bbenne10** [comment]
I'm happy to keep this **discussion** open, but I'm closing the ticket. It is not directly related to `nix-direnv`'s development. Please feel free to open a new ticket if you find that there's some issue with `nix-direnv` itself or to re-open this ticket if you feel I have closed it in error.

**Comment by Mic92** [comment]
> Sorry correction, the store file is not being garbage collected but it is still re-downloading the nix flake dependencies once a day.

Try the `--offline` flag to avoid this.

**Comment by jaybutera** [comment]
`--offline` also did not work. I think the problem is that `--profile` updates the gc root. So there was a gc root symlink for `python-flake`, `python-flake-1-link`, `python-flake-2-link`, and so on for every day it updated.

The solution is not to use `--profile` on every call to use flake. Just once at the beginning, manually run

```bash
nix print-dev-env --profile /nix/var/nix/gcroots/per-user/$USER/python-flake ~/.dotfiles/envs/python
```

And use the custom use-flake function below.

```bash
use_pythonflake() {
  watch_file ~/.dotfiles/envs/python/flake.nix
  watch_file ~/.dotfiles/envs/python/flake.lock
  eval "$(nix print-dev-env ~/.dotfiles/envs/python)"
}
```

This seems to work. I wonder if direnv could do anything to help with the manual process, perhaps a flag to add a gc root on `direnv allow`?
