### ISSUE TITLE
Question: Is it possible to get the drv without looking at $out?

### ISSUE THREAD

**Issue by bjornfor** [nix-community/nix-direnv#18]
I have a `shellHook` that sets `out=$PWD/_install` (and CMAKE_INSTALL_PREFIX=...) to allow running `genericBuild` inside nix-shell. But this breaks nix-direnv due to `$out` no longer pointing into the nix store, breaking this line in direnvrc:

```
drv=$(nix show-derivation "$out" | grep -E -o -m1 '/nix/store/.*.drv')
```

Is it possible to get the drv any other way?

**Comment by Mic92** [comment]
I am not aware of any other generic methods. You could define your variables, but this assumes a custom default.nix, so we cannot apply it in general. Maybe you can override `$out` in direnv instead of `shellHook`.

**Comment by Mic92** [comment]
Does this answer your question?

**Comment by bjornfor** [comment]
Yes, thank you. Too bad there is no generic solution.
