### ISSUE TITLE
Reloading .zshrc when using `use flake`

### ISSUE THREAD

**Issue by jmgilman** [nix-community/nix-direnv#184]
Hi,

This may be an edge-case, but I have a `flake.nix` which modifies `~/.zshrc` in the `shellHook` property. I was under the impression that when `direnv` loads the `devShell` environment that it would act as if a new shell was starting (i.e. reload `~/.zshrc` with the changes). However, either this is not the case, or it happens before the `shellHook` is executed. 

I've been trying various incantations to get the `~/.zshrc` file reloaded with the changes made by `shellHook` but so far I haven't been able to come up with anything. Perhaps there's a relationship between what `use flake` is doing with the `devShell` that might enable this functionality?

**Comment by bbenne10** [comment]
No - this is a limitation of the way that direnv works that we cannot work around.
Direnv works by spawning a bash subshell and saving a list of environment variables, running a few scripts (of which your `.envrc` is one) in that subshell and then extracting the changed environment variables. It then sets those environment variables in the outer shell. This means that it doesn't actually re-spawn any shells (which is effectively what you need to do to re-source `~/.zshrc`). 

There's nothing I can do about this, as it is an incompatibility between what you're expecting and the way direnv works.
