### ISSUE TITLE
Removal of NIX_BUILD_TOP always fails

### ISSUE THREAD

**Issue by abbec** [nix-community/nix-direnv#187]
After upgrading nix-direnv, I always get this error:

```
rmdir: failed to remove '/tmp/nix-shell.YgRKdf': Directory not empty
```

which causes a few variables (`$NIX_BUILD_TOP` among them) to not be re-set to their original values. The reason that the `$NIX_BUILD_TOP` that `nix print-dev-env` creates is not empty is that it dumps env vars to `$NIX_BUILD_TOP/env-vars` by default so the code [here](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L102) could never have worked properly.

If it is important that this dir is removed, `rm -rf` should probably be used there. Alternatively, you could set `noDumpEnvVars` to `1` before eval-ing the rc script.

**Comment by Mic92** [comment]
This is a left-over from back when it was not using `nix print-dev-env` but `nix-shell`

**Comment by bbenne10** [comment]
> This is a left-over from back when it was not using nix print-dev-env but nix-shell

I had assumed as much. If we wanted to keep anything that was ever found inside `$NIX_BUILD_TOP` we would not be `rmdir`ing it, and so figured it was safe to extend that to `rm -rf`. Thanks for the clarification!
