### ISSUE TITLE
Feature Request/Bug Report: Support for `--arg`/`--argstr`

### ISSUE THREAD

**Issue by m4dc4p** [nix-community/nix-direnv#190]
Pardon me if this has already been requested, or exists, but it doesn't seem like `use nix` passes along `--arg` or `--argstr`. Sometimes its useful to pass those arguments to `shell.nix`.

To demonstrate, first use this `shell.nix` which just prints the argument received:

```nix
{ arg ? "xxx" }:
let
  x = import <nixpkgs> {};
in 
  builtins.trace ("Got arg: ${arg}") x.bash
```

Then use this `.envrc` which passes the `SHELL_ARG` environment variable as an argument (if present) to `shell.nix`:

```bash
if [[ -n "$SHELL_ARG" ]]; then
    echo "Passing '$SHELL_ARG' to shell"
    use nix ./shell.nix --argstr arg $SHELL_ARG;
else
    echo "Not passing arg to shell"
    use nix ./shell.nix;
fi; 
```

Executing the following bash command should produce a trace showing the SHELL_ARG arg passed (`foo`), but instead you can see it's the default value (`xxx`):

```bash
$ export SHELL_ARG=foo; direnv allow
direnv: loading ~/.../.envrc
Passing 'foo' to shell
direnv: using nix ./shell2.nix --argstr arg foo
trace: Got arg: xxx
```

For completeness, using `nix-shell` directly shows the argument is printed:

```bash
$ nix-shell ./shell.nix --argstr arg foo
trace: Got arg: foo
```

**Comment by bbenne10** [comment]
Closed via #191. Please open a new issue if you find issue with the resolution.
