### ISSUE TITLE
Stale cache when using custom filename

### ISSUE THREAD

**Issue by jneem** [nix-community/nix-direnv#197]
I'm putting my shell configuration in `untracked-shell.nix` instead of `shell.nix` (and my `.envrc` contains `use nix untracked-shell.nix`). This works, except that edits to `untracked-shell.nix` don't trigger cache renewal: I need to `touch shell.nix` in order for those edits to take effect.

**Comment by Mic92** [comment]
This is a known design trade-of that was chosen in `nix-direnv`. See for more documentation and how deal with it: https://github.com/nix-community/nix-direnv/pull/199

**Comment by jneem** [comment]
Thanks for the quick reply! This will definitely improve my current setup.

Would you accept a PR that makes `use nix foo.nix` automatically add `foo.nix` to the tracked files?

**Comment by bbenne10** [comment]
@jneem: Indeed, we would.

Then again - I have the code locally and another change I'd like to get up (addressing a TODO in the codebase)

It is fully an oversight that the variable `nixfile` is not added to `watch_files`. 

I'll have a look shortly.

**Comment by bbenne10** [comment]
Sorry this has taken me so long. I have a fix for this and am working on getting test coverage for the feature. Will push as soon as I get the tests working.

**Comment by bbenne10** [comment]
Since life's gotten so busy - I am going to open an MR with this changeset in mind shortly. So sorry for the delay.
