### ISSUE TITLE
Creating gcroot for dev env

### ISSUE THREAD

**Issue by peterhoeg** [nix-community/nix-direnv#218]
I have done this in order to get a gcroot for the dev env. Am I missing an official way of doing this?

```nix
{
  programs.direnv.stdlib = ''
    register_gcroot() {
      local dir=/nix/var/nix/gcroots/per-user/$(whoami)
      local arch=$(uname -m)-$(uname -s | tr '[A-Z]' '[a-z]')
      local name=dev-$(systemd-escape --path $(git rev-parse --show-toplevel))

      test -d "$dir" || mkdir -p "$dir"

      nix build \
        .#devShells.$arch.default \
        --out-link "$dir/$name"
    }
  '';
}
```

And then inside each project `.envrc`:
```sh
if has nix; then
  if [ -f flake.nix ]; then
    use flake
    register_gcroot
  elif [ -f default.nix ]; then
    use nix
  fi
fi
```

**Comment by bbenne10** [comment]
You should not need to register a gcroot for nix-direnv. It will handle that for you.

Are you sure you're using nix-direnv and not the built-in flake support from direnv (which notably does NOT register a gcroot)?

**Comment by Mic92** [comment]
We also have a test to verify that: https://github.com/nix-community/nix-direnv/blob/b353b222c1624bc82fddbe7dc287a105354322c8/tests/test_gc.py#L46

**Comment by peterhoeg** [comment]
From my home manager config:

```nix
{  
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
}
```

So `use flake` should give me `nix-direnv`, no?

**Comment by peterhoeg** [comment]
And of course, the NixOS config:
```nix
{
  nix.extraOptions = ''
    keep-outputs = true
    keep-derivations = true
  '';
}
```

**Comment by Mic92** [comment]
If you have the correct nix-direnv you should see gcroots created like this in your project:

```
╭─[/etc/nixos]─[master*]
nix-shell ╰─ % ls -la .direnv
drwxr-xr-x joerg users  5 B  9 hours ago  ./
drwxr-xr-x joerg users 29 B  9 hours ago  ../
drwxr-xr-x joerg users 26 B  9 hours ago  flake-inputs/
lrwxrwxrwx joerg users 57 B  9 hours ago  flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa@ ⇒ /nix/store/y3l46bv9i99xph2017aq2p9rgriqcmgp-nix-shell-env
.rw-r--r-- joerg users 52 KB 9 hours ago  flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc
```

Also a bash function called `nix_direnv_version` should exists in your .envrc: https://github.com/nix-community/nix-direnv#direnv-source_url

**Comment by bbenne10** [comment]
I'm going to go out on a limb and say that either you *think* you are using `nix-direnv` and aren't, or you're using an old version that was bugged in this regard.

Given a week with no response - I am closing this for now. Please feel free to re-open if you can confirm that you're using the latest nix-direnv (or thereabouts).

**Comment by peterhoeg** [comment]
I really have no idea what is going on because it looks *partially* broken.

I am using nix-direnv from nixos-unstable so that should be the most recent version, but it looks like only the *inputs* are being kept and not the dev environments:

```
├── 1c50d02f9c3d8b603b08a3932ee3c546cb2e16a2                                                             
│  ├── flake-inputs                                                                                      
│  │  ├── j0r4c97k2iq55jymfkjxb2wzzjf19rpl-source -> /nix/store/j0r4c97k2iq55jymfkjxb2wzzjf19rpl-source
│  │  ├── nbph6bdglyhaid9cfbwiwby0fpy6ga6y-source -> /nix/store/nbph6bdglyhaid9cfbwiwby0fpy6ga6y-source  
│  │  └── wk1zs2zxcb53qzkil3xjfvbc2lv51qzd-source -> /nix/store/wk1zs2zxcb53qzkil3xjfvbc2lv51qzd-source
│  └── flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc                                       
├── 2c5f78861206fdd98b30517ead7e2d32d4f028d1                                                             
│  ├── flake-inputs                                                                                      
│  │  ├── 0cyniwphdgs58ib70v8sz6cd1vn1ri9v-source -> /nix/store/0cyniwphdgs58ib70v8sz6cd1vn1ri9v-source
│  │  ├── 0yqfkcplnfc8bcavi4jha7lnh0ig03za-source -> /nix/store/0yqfkcplnfc8bcavi4jha7lnh0ig03za-source
│  │  ├── aldaa87f8k1szqkgh1v8ngh4b35sk5g5-source -> /nix/store/aldaa87f8k1szqkgh1v8ngh4b35sk5g5-source
│  │  ├── i225h1qlm8bw3a2hlqpyqvf01qb7hf8x-source -> /nix/store/i225h1qlm8bw3a2hlqpyqvf01qb7hf8x-source
│  │  ├── l1gzyqkk5hkcdywnqglsjkd31w7g181x-source -> /nix/store/l1gzyqkk5hkcdywnqglsjkd31w7g181x-source
│  │  ├── lh2p0yaqdwib1wyn0kbgwncy3iwgzvc9-source -> /nix/store/lh2p0yaqdwib1wyn0kbgwncy3iwgzvc9-source
│  │  ├── xfw2zr3cqylwkhllqb81xgj4rv08w7px-source -> /nix/store/xfw2zr3cqylwkhllqb81xgj4rv08w7px-source
│  │  ├── xvqwca2j70brn1vznxxyc5wv13qz0gf1-source -> /nix/store/xvqwca2j70brn1vznxxyc5wv13qz0gf1-source
│  │  └── zdxim91q74d9j61z2z315jimi86ll82y-source -> /nix/store/zdxim91q74d9j61z2z315jimi86ll82y-source
│  ├── flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa -> /home/peter/.cache/direnv/layouts/2c5f78861206fdd98b30517ead7e2d32d4f028d1/flake-profile.1969141
│  └── flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc                                       
├── 2ef75cae4d017b67d81fba3099bd15943c56e0cd                                                             
│  ├── flake-inputs                                                                                      
│  │  ├── 5356r3f8pfz731rwcm1xrwaqqcbrq8gg-source -> /nix/store/5356r3f8pfz731rwcm1xrwaqqcbrq8gg-source
│  │  └── axki80c90fp5y3iq5i10ax99vij6h5av-source -> /nix/store/axki80c90fp5y3iq5i10ax99vij6h5av-source
│  └── flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc                                       
├── 29d04f96eeed47beaa55e749544ee6ffe2c04bf2                                                                                                                                                                      
│  ├── flake-inputs                                                                                      
│  │  ├── 1k4a1rknb1vid3r33sf92qs724ddcfjs-source -> /nix/store/1k4a1rknb1vid3r33sf92qs724ddcfjs-source
│  │  ├── 18yri7h9qqx5y58nr7a7ryl9cziyx96j-source -> /nix/store/18yri7h9qqx5y58nr7a7ryl9cziyx96j-source
│  │  └── 56phnjmz0f3wgaw1fx2z9r5dfyxsdr04-source -> /nix/store/56phnjmz0f3wgaw1fx2z9r5dfyxsdr04-source                                                                                                           
│  ├── flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa -> /home/peter/.cache/direnv/layouts/29d04f96eeed47beaa55e749544ee6ffe2c04bf2/flake-profile.2156874                                                 
│  └── flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa.rc 
```
I'm using a central cache location as outlined here: https://github.com/direnv/direnv/wiki/Customizing-cache-location

**Comment by peterhoeg** [comment]
I don't seem to be able to re-open the issue.

**Comment by bbenne10** [comment]
I am still not completely convinced that the version you're using is what you *think* you're using. 
Can you post your direnv configuration (not the nix version - the raw file, please) and the contents of the nix-direnv version you're using.

Assuming you're using home-manager, it should be generated and output into `~/.config/direnv/direnvrc`. 
If you're using nix-direnv, there should be a `source` line that points to `nix-direnv`'s direnvrc. 
If not - you're not (and you're using the builtin flake support from upstream direnv).
If so - what version is it?

**Comment by peterhoeg** [comment]
I think I have figured out what is going on here and it's not at all related to (nix-)direnv.

nix-direnv is being sourced correctly at the end of `direnvrc`.

This machine (midge the 2nd) has taken over from midge the 1st, which was severely space constrained. As a consequence, garbage collection was configured to run automatically.

midge (being a laptop and all) has `/home` on a LUKS volume and that combined with automatically powering on when the dock at home is plugged in, and I end up with garbage collection running, not being able to resolve the symlinks in and out of $HOME and all my environments getting cleaned up.

I can confirm that everything is working correctly now.

Thank you all!

```sh
: ${XDG_CACHE_HOME:=$HOME/.cache}
declare -A direnv_layout_dirs
direnv_layout_dir() {
  echo "${direnv_layout_dirs[$PWD]:=$(
    echo -n "$XDG_CACHE_HOME/direnv/layouts/"
    echo "$PWD" | sed -e 's/[^a-zA-Z0-9]/-/g' -e 's/^-//'
  )}"
}

# not needed anymore, nix-direnv handles it
register_gcroot() {
  echo "*** NOTICE Remove the call to register_gcroot ***"

  true
}

# forget about binstubs for projects with multiple Gemfiles as the binstubs would reference the last Gemfile read
layout_ruby-no-binstubs() {
  export GEM_HOME=$direnv_layout_dir/ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH

  PATH_add "$GEM_HOME/bin"
}

source /nix/store/radrq1wchkc2f4ishp2mhf4wvb322cd4-nix-direnv-2.1.2/share/nix-direnv/direnvrc
```

**Comment by bbenne10** [comment]
Glad you got it figured out! I'm sorry if I came off brusque - we deal with a fair number of tickets that end up not being nix-direnv related at all, so proving that it *is* in fact nix-direnv at fault is a big step up front. Thanks for your patience!

**Comment by peterhoeg** [comment]
No worries, thank you for nix-direnv!

Maybe this is the wrong place to have this discussion, but if we were to create the symlinks directly in the gcroots folder (basically anywhere under /nix), we would sitestep the problem of /home being available when GC runs. nixops does this and I have opened an issue with colmena as well.

**Comment by bbenne10** [comment]
I think that's going to need to be a new ticket just to keep discussion locally related. Please feel free to open that up.
