### ISSUE TITLE
nix_direnv_watch_file doesn't work

### ISSUE THREAD

**Issue by wmertens** [nix-community/nix-direnv#219]
See https://github.com/direnv/direnv/issues/979 - I'm trying to reload the flake when package-lock.json changes but I can't make nix-direnv do it.

**Comment by wmertens** [comment]
I was able to solve my issue by removing nix-direnv from my home-manager configuration, but it seems to me that that's still an issue? + I don't know if I won't want to use nix-direnv in the future :-)

**Comment by Mic92** [comment]
Use need to use `nix_direnv_watch_file` before `use flake`:

```
nix_direnv_watch_file package-lock.json
use flake
```

Otherwise it has no effect.

**Comment by tomdavidson** [comment]
Im not able to get the watch file to work either and I do have `use nix` last in the `.envrc`

**Comment by bbenne10** [comment]
@tomdavidson: This is certainly a regression somewhere and is a different base issue than this was. Can you please open a new issue documenting what you're doing and what you're seeing? Thank you.
