### ISSUE TITLE
Cleaning old GC roots ?

### ISSUE THREAD

**Issue by qaristote** [nix-community/nix-direnv#235]
If I list the profiles created by `nix-direnv` in one of my environments, here's what I get:
```
$ ls .direnv
aliases                            nix-profile-pre409534.f677051b8dc.rc  nix-profile-pre410680.a8a557e233c.rc  nix-profile-pre411003.72bdd03f0d5.rc
flake-profile.246679               nix-profile-pre410602.ae1dc133ea5     nix-profile-pre410722.e14f9fb5731     nix-profile-unknown.rc
flake-profile.246679-1-link        nix-profile-pre410602.ae1dc133ea5.rc  nix-profile-pre410722.e14f9fb5731.rc
nix-profile-pre409534.f677051b8dc  nix-profile-pre410680.a8a557e233c     nix-profile-pre411003.72bdd03f0d5
```
These profiles are all pointed to by a GC root so will not get cleaned after a `nix-collect-garbage -d`, yet I have strong reasons to believe most of them are actually profiles for older versions of my environment (they don't appear again if I delete them, their `buildInputs` do not match the current environment, I didn't find any part of `nix-direnv`'s code that deletes old roots) and are thus mostly useless.

Is there a way to have `nix-direnv` automatically delete these old profiles ? I could of course do something like `rm .direnv/nix-profile*` followed by `direnv reload` but maybe there's a better way ?

**Comment by dschrempf** [comment]
I was surprised that you have old configurations in your `.direnv` directories. For me this is not the case, it only stores the newest. (However, I use `use flake`).

**Comment by Snektron** [comment]
I have this same issue with `use flake`

**Comment by bbenne10** [comment]
I'm still working on some performance improvements for #227 in my downtime (and life is busier than ever right now). 
I'm happy to discuss and probably merge a pull request that deals with this shortcoming.

**Comment by bbenne10** [comment]
@qaristote's MR is now merged and I'm going to call this done! Thanks again, @qaristote :)
