### ISSUE TITLE
`argument list too long`

### ISSUE THREAD

**Issue by drupol** [nix-community/nix-direnv#239]
Hi,

I'm using `nix-direnv` in my projects and I usually create small Nix flakes so I can include them easily in `.envrc` files across all my projects.

Today, I tried to add a new line in the `.envrc` file and I got this error:

```
environment:1328: /nix/store/a0pzcp2iry0nz3cgnp3kbprnidsfw2s9-direnv-2.32.1/bin/direnv: Argument list too long
```

To reproduce the issue locally, create a `.envrc` file containing:

```
use flake github:loophp/nix-sphinx
use flake github:loophp/nix-prettier
use flake github:loophp/nix-auto-changelog
use flake github:loophp/nix-shell#env-php81-nts --impure
```

What can I do to prevent this?

**Comment by drupol** [comment]
According to @Mic92:
> these are limitations by the os. You can try to increase your stack size with `ulimit`, this is nothing in nix-direnv that I can do to fix this

**Comment by stephank** [comment]
I can't reproduce it with the snippet on either Linux or macOS, but wonder if we can't work around this some other way. From the output and reading the direnv / nix-direnv code, I don't understand what command exactly is the problem.

If we can pinpoint the command, maybe we could work around it with a solution like adding support for response files somewhere. (Like gcc / clang do, with `gcc @/path/to/argsfile`)

**Comment by drupol** [comment]
I was not able to reproduce it on an Ubuntu 22.04 running Nix.

The problem is on my personal laptop running NixOS unstable.
