### ISSUE TITLE
Utilise from outside `direnv`

### ISSUE THREAD

**Issue by ashleydavies** [nix-community/nix-direnv#251]
Hi! 👋🏻 Sorry for the potentially very naive question.

I was wondering how viable it is to utilise this project outside of `direnv`? Direnv serves 99% of my use cases, but there are times - for example, when configuring an IDE to execute a shell script with a `#!/usr/bin/env nix-shell` shebang - where I would love the ability to call into this caching functionality without necessarily going via `direnv`.

Is there presently any way to do this, and if not is it likely to be possible to support such a use case? From a total layman's perspective it feels like there must be some entry-point I could hook into, but for all I know that's sufficiently deep in the nettles that it's inaccessible

**Comment by bbenne10** [comment]
I am unaware of a way to reuse the functionality exposed here without direnv for a few reasons:

* direnv runs everything in an isolated bash shell, so this doesnt directly modify a user's shell or expose any way to do so.
* nix-direnv doesnt have any awareness of the calling context
* nix-direnv makes pretty extensive use of direnv's stdlib (which would need to be reimplemented to even begin to consider what you're asking aboit, I think)

Honestly, I think what you want is nix flake apps. They allow you to write "nix-native" shell scripts and to redistribute them as part of your flake.

**Comment by ashleydavies** [comment]
Makes sense - thank you for the detailed reply and suggestion @bbenne10!

**Comment by Mic92** [comment]
I consider this question answered.
