### ISSUE TITLE
nix-direnv version doesn't update when new releases are cut

### ISSUE THREAD

**Issue by hazelweakly** [nix-community/nix-direnv#258]
Hey there :)

It looks like the nix-direnv version hasn't updated since 2.1.0, so the ` ! nix_direnv_version 2.1.1` from the readme is unconditionally true and it'll always download the new script. Is this intentional?

(Additionally, a new release hasn't been cut in some time, but that's unrelated)

**Comment by Mic92** [comment]
I was not using the script lately when creating releases. This has been fixed now: https://github.com/nix-community/nix-direnv/releases/tag/2.2.0
