### ISSUE TITLE
Question: How do you flush the cache?

### ISSUE THREAD

**Issue by tartavull** [nix-community/nix-direnv#260]
Let's say you update `shell.nix` how do you flush the cache so that the changes apply?
Even better, is there a way to have some automatic reloading when you change not only shell.nix but the sources that goes into building the shell?

**Comment by bbenne10** [comment]
That should be done automatically for you. If not, it is likely a bug. Can you provide more information?

**Comment by Mic92** [comment]
For shell.nix this should happen automatically. For not tracked files you can run `touch shell.nix` to bust the cache.

**Comment by tartavull** [comment]
I really appreciate the help, it is working exactly as you described. Thank you!
