### ISSUE TITLE
shellHook environment variables missing in Fish shell

### ISSUE THREAD

**Issue by gvolpe** [nix-community/nix-direnv#263]
Given a simple `flake.nix` file defining a development shell with some environment variables in `shellHook`, these env vars are not exported properly when using Fish shell. 

However, running `nix develop` works properly. Using `direnv 2.32.1`, and `nix-direnv` managed by Home Manager. Current `nixpkgs` updated [2 weeks ago](https://github.com/gvolpe/nix-config/commit/a6135d1cbfeb245462503761fc0f28402e93cddb).

```nix
{
  description = "Direnv fish shell";

  inputs = {
    nixpkgs.url = github:nixos/nixpkgs/nixpkgs-unstable;
    flake-utils.url = github:numtide/flake-utils;
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem
      (system:
        let
          jreOverlay = f: p: {
            jre = p.jdk17_headless;
          };

          nodeOverlay = f: p: {
            nodejs = p.nodejs-16_x;
          };

          pkgs = import nixpkgs {
            inherit system;
            overlays = [ jreOverlay nodeOverlay ];
          };
        in
        {
          devShell = pkgs.mkShell {
            name = "scala-dev-shell";
            buildInputs = with pkgs; [
              jre
              sbt
              nodejs 
            ];
            shellHook = ''
              FOO=hey-foo
              JAVA_HOME="${pkgs.jre}"
              BAR=hey-bar
            '';
          };
        }
      );
}
```

Is this a known bug? Does it require some extra configuration for Fish?

**Comment by Gerschtli** [comment]
shellHook is bash code, that will not work for fish out of the box. I would recommend setting environment variables directly instead of misusing shellHook for that.

```nix
pkgs.mkShell {
            name = "scala-dev-shell";
            buildInputs = with pkgs; [
              jre
              sbt
              nodejs 
            ];
            
            FOO = "hey-foo";
            JAVA_HOME = pkgs.jre;
            BAR = "hey-bar";
          };
```

**Comment by gvolpe** [comment]
@Gerschtli thanks, I was not aware of this. I swear I thought I had this working in the past...

Is there any recommended solution, so this dev shell can be shared with bash/fish/zsh users? One of the environment variables we have is the result of the execution of a script. Something like:

```
MY_VAR=$(${pkgs.foo}/bin/foo)
```

**Comment by gvolpe** [comment]
Oh I misunderstood your answer, I guess putting them outside `shellHook` should be good?

**Comment by Gerschtli** [comment]
Not sure if there is Something like a shellHookFish. For dynamically computed env vars it could be tricky, don't know if there are other options tbh

**Comment by gvolpe** [comment]
Hmm perhaps I can have a little script in `shellHook` that determines what shell I'm in before evaluating the command that needs to set the environment variable

**Comment by gvolpe** [comment]
Hmm `$SHELL` and `$CONFIG_SHELL` always output `/bin/bash` even if I'm on Fish, so I don't know if this is possible

**Comment by gvolpe** [comment]
Ok, the solution was fairly easy. Leaving this here in case somebody else finds it useful.

```nix
pkgs.mkShell {
  name = "scala-dev-shell";
  buildInputs = with pkgs; [
    jre
    sbt
    nodejs 
  ];
  
  # static environment variables
  FOO = "hey-foo";
  JAVA_HOME = "${pkgs.jre}";
  
  # dynamic environment variables need to be exported explicitly    
  shellHook = ''
    export ACCESS_TOKEN=$(${scripts.foo}/bin/get-access-token)
  '';
}
```

**Comment by fcoury** [comment]
What if I need to add to an existing env var, like PKG_CONFIG_PATH?

**Comment by bbenne10** [comment]
Use the dynamic example above, referencing the existing variable:

```
 dynamic environment variables need to be exported explicitly    
  shellHook = ''
    export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:${whatever}
  '';
```

Assuming that your fish shell config exports the PKG_CONFIG_PATH into the spawned subshell

**Comment by bbenne10** [comment]
Honestly, I am unsure.
shellHook is always executed in bash so maybe source the venv's `activate` script (the posix one) from within shellHook? You may need to invrstigate what that script does and manually re-export some variables or something.

I had an example of this (admittedly a bash version) prior that I will try to find when I am up and moving. This basic problem is why we stopped doing venvs and started just using whatever version of the python lib is in nixpkgs. It is less choice up-front, but seems so far to be MUCH easier to maintain. You can even generate a requirements.txt and interact with the python packaging hellscape from a distance (mostly....c extensions are slightly harder to manage reproducibly).

We do this by maintaining a `buildPythonEnv` derivation with all of our dependencies in the devShell as an input and then extending PYTHONPATH with the src paths in subprojects from our monorepo.

(Please excuse typos. It is 6AM, Im on my phone, and github is not offering spelling help for some reason :P)

**Comment by bbenne10** [comment]
Note: I think this original problem is solved by prefixing the lines in the original shellHook each with `export` so that their values were caught by the invoking shell, bu maybe I am mossong something

**Comment by computerscience-person** [comment]
Using `nixpkgs.python3` is a good solution for personal use, but as I'm working with others on Windows, I'm stuck having to use cross-platform tools like `poetry` and `uv`, to at least regain some sanity in using Python dependencies. Its ultimately not a big deal, as it's only a single command to run at the end of the day.

**Comment by bbenne10** [comment]
I just looked and confirmed that sourcing the venv's activate script is essentially all we do (we have a bunch of other things that appease an ancient CI tool + local quirks, which is the complexity I was remembering).

Additionally, you could use direnv's builtin `layout python python3` (or similar, depending on your needs) from your `.envrc`.
