### ISSUE TITLE
how is nix-direnv invoked?

### ISSUE THREAD

**Issue by tomdavidson** [nix-community/nix-direnv#265]
Might be obvious, but Im a newb. How is `nix-direnv` invoked?

`direnv` calls `use flake` as configured in the `.envrc`

How does `nix` know about `nix-direnv`?

**Comment by Mic92** [comment]
direnv uses nix-direnv either through `use nix` or `use flake`. Nix does not need to know about `nix-direnv` as it is nix-direnv that calls out to nix and not the other way around.

**Comment by tomdavidson** [comment]
Oh gesh, I thought `use nix` was nix and not necessarily  nix-direnv.  Is that just newbie confusion or does nix-direnv override?

Thank you for the help!

**Comment by Mic92** [comment]
use_nix and use_flakes both have a direnv implementation and `nix-direnv` is replacing this implementation with an enhanced version:

```
$ direnv stdlib | grep -E 'use_nix|use_flake'
# Usage: use_nix [...]
use_nix() {
# Usage: use_flake [<installable>]
use_flake() {
```

**Comment by Mic92** [comment]
Also see the project description: https://github.com/nix-community/nix-direnv#nix-direnv
