### ISSUE TITLE
(Cosmetic issue) Filter which environment variables are exported?

### ISSUE THREAD

**Issue by Hubro** [nix-community/nix-direnv#278]
nix-direnv is really nice to use, but the thick block of environment variables that it pumps out really irks me:

```
direnv: loading /tmp/test/.envrc                                                                                                                             
direnv: loading https://raw.githubusercontent.com/nix-community/nix-direnv/2.2.0/direnvrc (sha256-5EwyKnkJNQeXrRkYbwwRBcXbibosCJqyIUuz9Xq+LRc=)
direnv: using nix
direnv: nix-direnv: renewed cache
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS
+NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_CC
+NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE
+NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_STORE +NM +NODE_PATH +OBJCOPY +OBJDUMP
+RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +XDG_DATA_DIRS +buildInputs +buildPhase
+builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget
+depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated
+doCheck +doInstallCheck +dontAddDisableDepTrack +mesonFlags +name +nativeBuildInputs +out +outputs
+patches +phases +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps
+system ~PATH
```

I have absolutely no clue what 95% of these environment variables do. All it does it flood my terminal any time I open a project.

The only variables I see here that I care about are

- `PATH`
- `NODE_PATH`
- `XDG_DATA_DIRS`
- `IN_NIX_SHELL`

How many of the other variables are necessary for nix to function, if any? Is there a way I can whitelist which variables should be set through direnv, to limit the noise?

---

`.envrc`:

```bash
# Enables "use nix"
source_url \
  "https://raw.githubusercontent.com/nix-community/nix-direnv/2.2.0/direnvrc" \
  "sha256-5EwyKnkJNQeXrRkYbwwRBcXbibosCJqyIUuz9Xq+LRc="

use nix
```

`default.nix`:

```nix
{ pkgs ? import (fetchTarball "http://nixos.org/channels/nixos-22.11/nixexprs.tar.xz") {}}:

pkgs.mkShell {
  nativeBuildInputs = [
    pkgs.nodejs-18_x
    pkgs.nodePackages.pnpm
  ];
}
```

**Comment by Mic92** [comment]
We cannot make the decision in nix-direnv which environment variables are necessary for your nix-shell to function.
This is up-to-the user to decide and what type of derivation to provide. Many of these variables comes from `stdenv.mkDerivation` and are necessary for the c/c++ infrastructure to work. If you don't care about C/C++ you can also use project like devenv or devshell, which use a more minimal shell called naked shell. Also this definition: https://github.com/numtide/devshell/blob/master/nix/mkNakedShell.nix

**Comment by Hubro** [comment]
Oh, that's not what I was suggesting, I was hoping for some mechanism for me to personally whitelist which environment variables I want 🙂 Or some suggestion for how I could achieve this on my own.

I'm moving towards using Nix on every project I work on, since it removes the need for a bunch of tools like NVM, pyenv, Node (for installing Tailwind or SASS), RVM and so on.

This means I'll soon have this big, thick wall of environment variables in my face every time I open a terminal in any of my projects, which is just frustrating. The block obfuscates any information I may have gotten from that log line line to the point where I'd rather just remove the whole thing if that was possible.

If I could somehow specify that I'm only interested in the `PATH` variable and nothing else, I think that would be very valuable.

**Comment by Mic92** [comment]
I don't think I want add an API for this since it would diverge to much from direnv's own `use nix` , but you can simply do this:


```
export PATH=$(use nix; echo "$PATH")
```

**Comment by Hubro** [comment]
> I don't think I want add an API for this since it would diverge to much from direnv's own `use nix` , but you can simply do this:
> 
> ```
> export $(use nix; echo "PATH=$PATH", echo "NODE_PATH=$NODE_PATH")
> ```

Aha, that's clever, thanks! Hopefully I can make a nice API for this in my direnvrc :slightly_smiling_face:

**Comment by Mic92** [comment]
I guess one could make a case that some mechanism like this could be part of direnv's stdlib.
