### ISSUE TITLE
IN_NIX_SHELL should be pruned

### ISSUE THREAD

**Issue by fzakaria** [nix-community/nix-direnv#28]
I noticed that in my env `IN_NIX_SHELL=pure` after using this plugin; but that seems incorrect since the premise of this plugin is to merge the NIX_SHELL into your other shell; making it impure.

Might be worthwhile to purge this variable from the environment dump.
It was very noticeable because my ZSH theme was picking up that environment variable and displaying it.

![image](https://user-images.githubusercontent.com/605070/87331562-077bc080-c4ef-11ea-8b05-385fd1303a6a.png)

**Comment by Mic92** [comment]
Maybe `nix-shell --pure` should not be used? What also could work is `env - nix-shell`?

Any opinions on this @zimbatm?

**Comment by Mic92** [comment]
Actually `env -i` will break the NIX_PATH, so it is not a solution either.

**Comment by Mic92** [comment]
Does it have any negative impact though or is it just cosmetics?

**Comment by fzakaria** [comment]
I'm not sure at that point within the shell if `IN_NIX_SHELL` has any effect aside from cosmetics.
It's definitely not a pure shell though when used with _dir-env_ since I have access to all my system-wide programs etc...

This is probably a symptom of dir-env having nix-shell export it's pure environment into a non-pure enviornment.
However at that point...it's definitely not pure so how about it's just pruned/filter?

**Comment by Mic92** [comment]
I am a bit reluctant to prune it without a good reason that because nixpkgs already uses `IN_NIX_SHELL` checks to change its execution flow and changing it afterwards might have side-effects.
It's also consistent with the upcoming `nix print-dev-env`.

**Comment by zimbatm** [comment]
`nix-shell --pure` doesn't make a lot of sense in the context of direnv. Do you not want to have your editor available inside of the project?

**Comment by Mic92** [comment]
> `nix-shell --pure` doesn't make a lot of sense in the context of direnv. Do you not want to have your editor available inside of the project?

This is not what happens here. We use environment variables from `nix-shell --pure` and cache its result. If we would use `nix-shell` without `--pure` we would also cache user defined variables such as `EDITOR` and merge those back into the environment when reading the cache.

**Comment by zimbatm** [comment]
I see. Maybe set `IN_NIX_SHELL=impure` then?

**Comment by Mic92** [comment]
Not sure how to apply this: 

```console
$ IN_NIX_SHELL=impure nix-shell --pure --keep IN_NIX_SHELL --run 'echo $IN_NIX_SHELL'
pure
```

**Comment by fzakaria** [comment]
Why can't direnv just change it after the export before it applies it & caches it. 

IMO it's more "correct" about the state of affairs setting it to impure afterwards. 

This is kind of bike sheddy sorry.

**Comment by zimbatm** [comment]
I was thinking the same, dump and restore the `nix-shell --pure`, and then `export IN_NIX_SHELL=impure`

**Comment by fzakaria** [comment]
I opened up the pull-request linked to do what's discussed @zimbatm ; pretty straightforward change.
