### ISSUE TITLE
error: attempt to call something which is not a function but a set

### ISSUE THREAD

**Issue by yajo** [nix-community/nix-direnv#285]
I use flakes with https://github.com/edolstra/flake-compat to get the good things of flakes while still having backwards compatiblity.

Thus I'd love to `use nix` instead of `use flake`, so I get broader compatibility.

My `shell.nix` looks like this:

```nix
(
  import
  (
    let
      lock = builtins.fromJSON (builtins.readFile ./flake.lock);
    in
      fetchTarball {
        url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
        sha256 = lock.nodes.flake-compat.locked.narHash;
      }
  )
  {src = ./.;}
)
.shellNix
```

When installing nix-direnv, I get this error with `direnv allow`:

```
➤ direnv allow
direnv: loading ~/mydevel/copier/.envrc
direnv: using nix -A devShells."x86_64-linux".default
warning: Git tree '/var/home/yajo/mydevel/copier' is dirty
error: attempt to call something which is not a function but a set

       at «string»:1:2:

            1| (import ./shell.nix {}).devShells."x86_64-linux".default
             |  ^
direnv: nix-direnv: renewed cache
direnv: export ~XDG_DATA_DIRS
```

It seems that it's trying to call `shell.nix` with an empty set `{}`, but `shell.nix` is not a function.

**Comment by yajo** [comment]
As a workaround, I converted `shell.nix` to a function. However, it seems like it is still a bug, as it works fine with all other shell tools, like `nix-shell`. This is how it looks now:

```nix
{lock ? builtins.fromJSON (builtins.readFile ./flake.lock)}:
(
  import
  (
    fetchTarball {
      url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
      sha256 = lock.nodes.flake-compat.locked.narHash;
    }
  )
  {src = ./.;}
)
.shellNix
```

**Comment by Mic92** [comment]
Is there any still supported nix version that does not flakes? I think we are about to kickout nix 2.3 from nixpkgs as well. `use flake` should also enable experimental flags needed to load the flake.

**Comment by bbenne10** [comment]
Is this still a problem with latest nix versions (2.10 minimum) and nix-direnv versions?

**Comment by Mic92** [comment]
Probably not.

**Comment by CobaltCause** [comment]
This is still a problem. Using `use nix` with `-A foo.bar` with a nix expression that is not a function results in this code path being hit:

https://github.com/nix-community/nix-direnv/blob/38883833413a601fb64f51cd33e4fa0ffbc33320/direnvrc#L499

which doesn't work because the nix expression is not a function. Passing `{}` like that should probably be conditional on `builtins.isFunction`. Would a PR to make such a change be accepted?

**Comment by CobaltCause** [comment]
A workaround is to edit `~/.config/direnv/direnvrc` and change:

```bash
source /path/to/nix-direnv/direnvrc
```

to:

```bash
# See <https://stackoverflow.com/a/34177402> for details.
_rename_fn() {
    local a
    a="$(declare -f "$1")" &&
    eval "function $2 ${a#*"()"}" &&
    unset -f "$1";
}

# Save direnv's `use_nix`.
_rename_fn use_nix direnv_use_nix

source /path/to/nix-direnv/direnvrc

# Overwrite nix-direnv's `use_nix` with direnv's `use_nix`.
_rename_fn direnv_use_nix use_nix
```

Or just uninstall nix-direnv.

**Comment by bbenne10** [comment]
> Would a PR to make such a change be accepted?

Dependent on quality, but likely.
