### ISSUE TITLE
Error when no `nix-channels` are configured

### ISSUE THREAD

**Issue by FPtje** [nix-community/nix-direnv#286]
When both `nix-channel --list` and `sudo nix-channel --list` give no result (i.e. no channels configured), the following error is thrown when using `use nix` in a `.envrc` file:

```
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
realpath: '': No such file or directory
```

Some people may not have a nix channel, because they use flakes, and/or the newer `nix profile`. When the repository then also uses a pinned version of Nix (through e.g. also flakes or via `niv`), then there is really no need to even try anything with installed channels. 

The place where it errors (I believe) is here:

https://github.dev/nix-community/nix-direnv/blob/b583f373027eb449737fd68bba1386b0741b713b/direnvrc#L256

The workaround I use is as follows, but it is pretty ugly:

```
NIX_PATH='nixpkgs=/dev/null' use nix default.nix
```

**Comment by Mic92** [comment]
Addressed in https://github.com/nix-community/nix-direnv/pull/287

**Comment by Mic92** [comment]
Closing because a new release does include this.
