### ISSUE TITLE
should ldd be /usr/bin/ldd

### ISSUE THREAD

**Issue by fzakaria** [nix-community/nix-direnv#30]
I have a _philosophical_ question here about how direnv & nix-shell interoperate.

My understanding is that direnv should be bringing in the defined tooling that was defined in **shell.nix** to allow a more seamless **impure** development environment (allows running in the user's predefined shell).

I faced an interesting dilemma when trying to run a binary within my direnv'd shell:  [BeyondCompare](https://www.scootersoftware.com/) -- a diffing tool.
**This is a personal tool I have installed outside the world of Nix**

The application has a wrapper script which does the following:
```bash
#check to see if we have all of the shared libraries.
if ldd "$EXEC" | grep -q "not found" ; then
   #if not then add our qt4 libraries in and see if that fixes problem
   export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$BC_LIB/qt4"
   if ldd "$EXEC" | grep -q "not found" ; then
       echo Some Shared Libraries were not found
       ldd "$EXEC"
        exit 1
   fi
fi
```

The above looks pretty sane; it just wants to guarantee that the required libraries are present and modify the LD_LIBRARY_PATH if so.

Unfortunately, since **ldd** in my direnv'd shell is the _/nix/store_ one; it's patched to **only look in /nix/store** for libraries.

```
$ which ldd
/nix/store/3imnvgp2dkfpsi75ygmgksn16nksf6ls-glibc-2.30-bin/bin/ldd

$ ldd /usr/lib/beyondcompare/BCompare
	linux-vdso.so.1 (0x00007f9e17b12000)
	/lib/x86_64-linux-gnu/libnss_cache.so.2 (0x00007f9e17b05000)
	librt.so.1 => /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/librt.so.1 (0x00007f9e17afb000)
	libbz2.so.1.0 => not found
	lib7z.so => not found
	libpthread.so.0 => /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libpthread.so.0 (0x00007f9e17ada000)
	libc.so.6 => /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libc.so.6 (0x00007f9e1791b000)
	libdl.so.2 => /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib/libdl.so.2 (0x00007f9e17914000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/bqbg6hb2jsl3kvf6jgmgfdqy06fpjrrn-glibc-2.30/lib64/ld-linux-x86-64.so.2 (0x00007f9e17b14000)
	libQt4Pas.so.5 => not found
	libX11.so.6 => not found
	libz.so.1 => not found
```

```
$ /bin/ldd /usr/lib/beyondcompare/BCompare
	linux-vdso.so.1 (0x00007ffc5e0b0000)
	/lib/x86_64-linux-gnu/libnss_cache.so.2 (0x00007f74f5fbb000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f74f5f96000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f74f5f83000)
	lib7z.so => not found
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f74f5f62000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f74f5d9f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f74f5d98000)
	libQt4Pas.so.5 => not found
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f74f5c56000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f74f5c39000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f74f5fc4000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f74f5c0f000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f74f5c08000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f74f5c00000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f74f5be6000)
```

Since the whole premise of direnv is to bring in the defined software in an impure fashion; should **ldd** be unset in this case to allow this program to function?

**Comment by fzakaria** [comment]
Little follow-up:

I understand that nix-shell is to help you _debug_ work through building a derivation however that's almost at odds with in which the way direnv + _mkShell_ are used. They are more to bring in tooling such as Ruby or Java.

I'm a little stumped here though if you really wanted the /nix/store ldd.

**Comment by Mic92** [comment]
It's part of glibc/stdenv. If we don't add it than results will be inconsistent across platforms, which we want to avoid in the first place. Also removing `glibc/bin` is not trivial. If you really don't want glibc in our output you should remove it from PATH again in a custom shell hook:

```
mkShell {
  shellHook = ''
    to_remove="${stdenv.cc}/bin"
    # some bash magic to purge it from $PATH
  '';
}
```

Maybe you can install your tool with nix somehow.

**Comment by fzakaria** [comment]
@Mic92 that makes sense except that the use of direnv with Nix is a weird blend of impure _nix-shell_ + your default shell.
Given that it's impure seems okay to make **ldd** the **/usr/bin/ldd** version to allow non /nix/store library resolution.

Anyways it was somewhat philosophical on using direnv for development; feel free to close.
I'm enjoyed the discussion.
