### ISSUE TITLE
Does nix-collect-garbage clear nix-direnv's cache?

### ISSUE THREAD

**Issue by giang-nghg** [nix-community/nix-direnv#302]
If not, how do I clear the cache once I no longer need an environment?

**Comment by bbenne10** [comment]
TL; DR: If you clear your direnv cache for a particular environment, garbage collection will remove the environment.

Long version: We create a gcroot symlink as part of the direnv cache. This keeps the (latest) environment alive as long as there exists some direnv cache for that project. Removing the direnv cache directory will remove the symlink, which will then let garbage collection know that it can remove the environment in question.
