### ISSUE TITLE
Support `--ignore-environment`

### ISSUE THREAD

**Issue by evertedsphere** [nix-community/nix-direnv#306]
With `use flake`, it would be great to have the ability to enter an `--ignore-environment` shell.

**Comment by bbenne10** [comment]
I'm not going to make a final call on this (Will leave that to @Mic92) but frankly, I am not entirely sure I see the point of doing this. Not to say that some use case does not exist, but why not just call `nix shell --clear-environment` in a project root (or override your shell's `cd` to do so for you or something)? It doesn't seem like a pure environment is at all what we're going for here. We exist to mix your shell and a development environment.

I'm not even sure how I'd go about implementing this, seeing as we're backed by `print-dev-env`, which lacks the option to clear the environment. That and how direnv handles the exporting of environment variables: it will shadow new versions of variables, but I don't think you can *clear* them without explicitly calling something like `unset`? So we'd need to...iterate all of the environment variables present in the current shell(excluding the `--keep` ones, I presume) and then echo out a templated string that unsets those variables. This approach doesn't handle *new* environment variables (say you `cd`'d into the directory with `foo` and `bar` set and then again with `foo`, `bar` and `baz` set - we'd allow `baz` through in this approach)

Caching makes this harder and I'm not sure it is worth the effort for me to implement. I will happily review any PR that adds this functionality though.

**Comment by Mic92** [comment]
I prefer not implement features that significantly change the behavior and are not present in the original direnv stdlib version so that it can stay a drop-in replacement.
