### ISSUE TITLE
How do I know if I've set it up correctly?

### ISSUE THREAD

**Issue by dpc** [nix-community/nix-direnv#315]
I'm using `fish` as my default shell. But I think since I added `source /run/current-system/sw/share/nix-direnv/direnvrc` to my `.bashrc` then `direnv` will automatically source that (as it internally uses `bash`, right?).

Anyway ... things seems to work now, but how do I know if I'm using original `direnv` flake support or the `nix-direnv`'s one? Is there like an env variable I can check?

**Comment by dpc** [comment]
Well, since I don't see anything added to `/nix/var/nix/gcroots/per-user/dpc/` (and neither to the new location under `$HOME/` that is in the plans), I guess my `.bashrc` is not being sourced actually.

**Comment by dpc** [comment]
Right, I'm actually using the [direnv fish setup](https://github.com/direnv/direnv/blob/master/docs/hook.md#fish), so that kind of explains it.

**Comment by bbenne10** [comment]
Sourcing the provided direnvrc is...non-standard and a bit odd. It is intended to be included in the direnv config script (at `~/.config/direnv/direnvrc`). I think that the README makes this pretty clear.

Specifically, the `with nix-profile` section documents where to place this file (but documents an old location for the direnv configuration. We should update that! Please use `~/.config/direnv/direnvrc`!). Can you place the snippet in the right spot and report back?

**Comment by dpc** [comment]
> Sourcing the provided direnvrc is...non-standard and a bit odd. It is intended to be included in the direnv config script (at ~/.config/direnv/direnvrc).

I'm sorry. I have missed that. Makes sense.

After I did what you told me, I do see some entries in `/nix/var/nix/gcroots/per-user/dpc` which weren't there before, so I think it works!

Thanks a lot!

BTW. [The seems like the location of these entries will move in the future](https://github.com/NixOS/nix/pull/5226), while the script seems to be hardcoding the old one if I'm reading it right.

**Comment by bbenne10** [comment]
Great! Glad it's working for you.

Regarding the change to nix profile location: #311 aims to address that, but we're having some trouble with maintaining the gcroot after collection. If you have ideas, please comment there and we'll restart conversation there. I intend to work on that in some free time soon.
