### ISSUE TITLE
direnv not accepting flake config

### ISSUE THREAD

**Issue by iburzynski** [nix-community/nix-direnv#336]
I'm using a Nix flake with nix-direnv. My flake contains `nixSettings`, including a `bash-prompt` and some `extra-trusted-substituters`/`extra-trusted-public-keys` settings. I would like these settings to be accepted automatically whenever the nix shell is loaded via direnv.

If I run `nix develop --accept-flake-config` the flake settings are applied, but navigating into the directory and loading the environment via direnv ignores the flake config.

These are the contents of my `.envrc` file:

```
if ! has nix_direnv_version || ! nix_direnv_version 2.2.1; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.2.1/direnvrc" "sha256-zelF0vLbEl5uaqrfIzbgNzJWGmLzCmYAkInj/LNxvKs="
fi

use flake . --accept-flake-config
```

Is it possible to make direnv accept the flake config? It's critical that my dev environment always apply the flake settings, so the bash prompt indicates that users are inside the develop shell and to prevent them needing to configure the extra substituters in `nix.conf`.

**Comment by bbenne10** [comment]
I keep trying to leave this comment and accidentally closing the tab when I leave to check on something or another for it. Let's see if the 4th time is the charm.

Reading our implementation, I can verify that we are passing `$@` (which will contain `--accept-flake-config`) to the invocation of `nix print-dev-env`. See [here](https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L207) for confirmation. What exact behavior are you seeing that is different between the `nix develop` and `nix-direnv` invocations? Can you confirm that the output of `nix print-dev-env . --accept-flake-config` differs meaningfully from `nix print-dev-env .`? 

I am - unfortunately - quite busy and will be getting busier shortly, but I will lay out how I'd start to debug this in case someone has some time to get to it:

* First, see how the resultant environment script differs when invoking `nix print-dev-env` with and without the `--accept-flake-config` argument. 
* Secondly, I would check how the scripts net results interact with `_nix_import_env`. Does it modify the things we override/reset after sourcing it? I wouldn't expect it to, but...maybe?
* Thirdly, I'd start with `set -x` in our direnvrc and then start adding `echo` calls to figure out how we're clobbering the resultant environment (after maybe REALLY making sure that line 207 is invoking `nix print-dev-env` with the expected arguments)

I don't pretend to be an expert though. Someone may be able to come in behind me and say that it is very obvious why this isn't working. I'm sorry to not be more help right now. I will look into this when I find some time.

**Comment by iburzynski** [comment]
Thanks @bbenne10, this is very helpful!

I saved the outputs of `nix print-dev-env . --accept-flake-config` and `nix print-dev-env .` to files and diffed them. It turns out they're identical, so it appears the issue isn't with how nix-direnv is calling `print-dev-env`, but with Nix itself not actually doing anything with the `--accept-flake-config` argument (despite it being listed as an option for `print-dev-env` here: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-print-dev-env.html).

I'm not sure how I should proceed now. I really need the flake config to be accepted, but if the underlying command isn't capable of doing this then I may be SOL.

**Comment by bbenne10** [comment]
I think it warrants further introspection into how `accept-flake-config` interacts with `print-dev-env`, but something like https://github.com/nix-community/nix-direnv/issues/324#issuecomment-1490085474  might help in the meantime? (Note that this is pretty restricted since it is zsh only and requires changing a user's zsh configuration directly).

**Comment by iburzynski** [comment]
Thanks for the suggestion. I tried adding a bash function to `.bashrc` to override the `cd` command like this:

```
cd() {
  builtin cd "$@" || return
  [ "$OLDPWD" = "$PWD" ] || if test -f flake.nix; then nix develop . --accept-flake-config; fi
}
```

This works, but is undesirable obviously. It requires modifying the user's `.bashrc` and it's dangerous to have any directory containing a flake simply run it with accepted flake config. I'm also losing all the benefits of nix-direnv in terms of caching, persistence, etc. My project relies on direnv and the contents of `.envrc` quite heavily, not just for loading the flake, so this approach would entail me still using direnv but replacing the otherwise wonderful Nix support with this hacky/dangerous workaround.

I may have to give up on this idea - the problem is my users struggle with properly configuring binary cache and frequently end up spending hours building packages from source. My ideal scenario is for them not to touch `nix.conf` at all and let the flake handle everything.

**Comment by bbenne10** [comment]
There's also the possibility of using `nix develop --accept-flake-config .` in an `.envrc`. 
Note that this gives up the user's shell configuration and enforces bash. 

I'm sorry that I don't presently have a better answer.
I hope to look into this soon-ish, but family matters are taking up a lot of time.

**Comment by iburzynski** [comment]
You're right, in this case that seems like the best alternative. Thank you so much - you've been very generous with your time and it's much appreciated! I have a much better understanding of how everything works now.

**Comment by bbenne10** [comment]
The comment you're likely replying to is deleted. For good reason too! I don't think it'll work!

(For those reading along later: I suggested that you use `nix develop ...` inside an `.envrc` invocation to simulate what nix-direnv does)

Direnv spawns a bash shell and records the environment going into and out of that subshell. Spawning a long running (and blocking) process inside that shell is asking for trouble, I think. I don't think that direnv attaches the user to the shell it spawns so you'll likely just either error out or get stuck without the ability to interact with it. 

You're welcome to try - but I did warn you :P

**Comment by Mic92** [comment]
Notice that bash-prompt does only get applied in `nix develop` but not in `nix print-dev-env`. I think `extra-trusted-substituters` should work nevertheless

**Comment by bbenne10** [comment]
A good point that I was taking for granted. 

I should've mentioned that I think that the *flake interfacing options* that `accept-flake-config` allows should work, but the ones that interact with the shell will fail.

**Comment by bbenne10** [comment]
If you've run the derivation before, nix will cache the results and running with or without the substituters will not mean anything as you'll never hit them. Once you've grabbed the built derivations from a substituter, the net local state is the same between execution paths. 

And no - `use_{nix,flake}` doesn't allow exporting a prompt because of the manner in which we collect the environment. However, you should be able to export one *after* calling `use_{nix,flake}` inside `.envrc` as shown:

```zsh
nix_direnv_watch_file $(find . -name *.nix)
use_flake

# May want this to be PS1 depending on shell
export PROMPT="SOME FANCY PROMPT >"
```

**Comment by iburzynski** [comment]
I've tried exporting both `PROMPT` and `PS1` in `.envrc` and neither of them have any effect - the default bash prompt still displays. The custom prompt is less of a concern for me though - I'm more concerned with having `extra-substituters` from the flake config be accepted (not `extra-trusted-substituters` as I wrote previously - I was mixing up these settings).

Here's my situation now:
* I was incorrectly assuming that `print-dev-env` would accept the `bash-prompt` setting and was thus using that as an indicator of whether the flake config was being accepted.
* I already had the `substituters` and `trusted-public-keys` that I was looking to accept via the flake enabled globally via `configuration.nix`, which obscured whether the extra values in the flake config were actually being accepted.
* I removed these from `configuration.nix` and ran `nix show-config` to confirm they're not being applied. Then I entered my project directory and I'm getting cache hits on the substituters, so it seems the flake config is in fact working.
* However I'm currently not calling `use flake` with `--accept-flake-config` in my `.envrc`, so I assume the reason the flake settings are applying is due to me previously accepting this config. *Can you explain how I can revoke this so I have a clean slate and can properly test that things are working?*
