### ISSUE TITLE
flake build error wasn't surfaced until I manually ran `nix-shell`

### ISSUE THREAD

**Issue by colemickens** [nix-community/nix-direnv#34]
I've got something messed up in my `flake.nix`. I think `nix-direnv` is sort of hiding it from me:

```

> cd code/nixpkgs-wayland
cd: no such file or directory: code/nixpkgs-wayland
direnv: loading ~/code/nixpkgs-wayland/.envrc                                                                                                                                     
direnv: using flake
warning: Git tree '/home/cole/code/nixpkgs-wayland' is dirty
error: --- SysError ---------------------------------------------------------------------------------------------------------------------------------------------------------- nix
getting attributes of path '/nix/store/pbcaa4p55p11x7f1hb53iknzmi2vhm33-source': No such file or directory
(use '--show-trace' to show detailed location information)
direnv: renewed cache

> nix-shell
warning: Git tree '/home/cole/code/nixpkgs-wayland' is dirty
error: --- ThrownError ------------------------------------------------------------------------------------------------------------------------------------------------- nix-shell
flake input has unsupported input type 'path'
(use '--show-trace' to show detailed location information)

```

**Comment by Mic92** [comment]
What does `nix develop` outputs?

**Comment by colemickens** [comment]
I'm not sure, it's too late. FWIW, I think my `nix-shell` is wired up to that, it uses flakes-compat:

```
(import (fetchTarball {
  url="https://github.com/edolstra/flake-compat/archive/c75e76f80c57784a6734356315b306140646ee84.tar.gz";
  sha256="071aal00zp2m9knnhddgr2wqzlx6i6qa1263lv1y7bdn2w20h10h";
}) {
  src = builtins.fetchGit ./.;
}).shellNix
```

**Comment by Mic92** [comment]
So you are using `use nix` or `use flakes` here?

**Comment by colemickens** [comment]
I am using `use flake` (vs "flakes"). I switched everything to nix-direnv and flakes system-wide yesterday.

**Comment by Mic92** [comment]
Looks like some sort of import from derivation does not work here?

```
getting attributes of path '/nix/store/pbcaa4p55p11x7f1hb53iknzmi2vhm33-source': No such file or directory
```

**Comment by colemickens** [comment]
Just to make sure I've explained this enough:

The `flake.nix` was malformed, but for some reason `nix-direnv` failed to surface that error and instead showed `getting attributes of path '/nix/store/pbcaa4p55p11x7f1hb53iknzmi2vhm33-source': No such file or directory`. But `nix-shell` was able to show the correct message about the flake.nix being malformed. Even though they both load from the `flake.nix`, as far as I understand.

This isn't something that `nix-direnv` can fix?

**Comment by Mic92** [comment]
So this bug is about `nix print-dev-env` creating different error messages than `nix-shell`. I don't think I change much about the error message here.

**Comment by colemickens** [comment]
Okay, I see. Thank you for taking the time to look at it. I might file against nixos/nix.
