### ISSUE TITLE
.direnv directory cluttering up project

### ISSUE THREAD

**Issue by l0b0** [nix-community/nix-direnv#340]
After enabling nix-direnv my projects are getting cluttered with a .direnv directory. Is this normal? Because it's not mentioned in the readme.

**Comment by aisamu** [comment]
That's related to `direnv` the underlying tool. 
Here's some info, including how to fix it:
https://github.com/direnv/direnv/wiki/Customizing-cache-location

**Comment by l0b0** [comment]
Excellent, thank you for that!
