### ISSUE TITLE
New version detection code breaks ZSH compatibility

### ISSUE THREAD

**Issue by polygon** [nix-community/nix-direnv#349]
Not sure if ZSH is an actually supported target, but I found `nix-direnv` to usually work fairly well with ZSH. Unfortunately, the new version detection code seems to use `BASH_REMATCH` in order to do the version detection which is not available by default on ZSH and hence, environment activation can fail unless ZSH is specifically configured with

```
setopt BASH_REMATCH
```

I think we could check if we are running inside ZSH in `_nix_direnv_preflight` and then enable compatibility mode only for this function with `setopt local_options BASH_REMATCH`. If this project wants to support ZSH, I can test this further and make a pull request.

**Comment by bbenne10** [comment]
I'm now quite confused. We've had `BASH_REMATCH` in the codebase longer than your complaint indicates and this got me thinking: How are you sourcing `nix-direnv`? Because the shell that's invoked by direnv should always be bash.

**Comment by Mic92** [comment]
Yes. nix-direnv never needs to run in zsh. direnv integration will export variables generated by the .envrc into the user's shell.

**Comment by Mic92** [comment]
Closing. But feel free to describe how you are actually using nix-direnv just now.
