### ISSUE TITLE
Allow specifying lock file to use with `use flake`

### ISSUE THREAD

**Issue by ehamberg** [nix-community/nix-direnv#361]
In some projects, I use some extra tools that I don't want to include in the dev shells of a project, since not all developers would want them. In those cases, I use a `.envrc` file with two `use flake statements:

```
use flake ~/nix/my-dev-utils
use flake .
```

However, for some tools, the versions should also stay in sync, so Ideally I'd like the “dev utils” flake to use the same lock file as the project's lock file.

What I *think* I want is support for passing the [`--reference-lock-file`](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake-lock.html) argument to `nix flake`, so the `.envrc` file above would look something like this:

```
use flake ~/nix/my-dev-utils --reference-lock-file ./flake.lock
use flake .
```

Is this something that it would make sense to support?

**Comment by bbenne10** [comment]
Isn't this already possible?
All arguments are proxied along to `print-dev-env` (including `--reference-lock-file`).
Have you tried doing exactly what you wrote?

I suspect you'll have the same trouble mentioned in #341 (and maybe a specific set of issues exposed by possibly overlapping the two sets of inputs).

**Comment by ehamberg** [comment]
I got an “unrecognised flag” error, but I now realize that this probably comes from `nix` directly, and that the version that gets used (through home-manager `direnv` module and its `nix-direnv` option) is probably too old.

```
error: unrecognised flag '--reference-lock-file'
Try '/nix/store/p88ixyw28skf5zvl6lbqh79w277y86fy-nix-2.13.3/bin/nix --help' for more information.
```

The issue you pointed me to made me have second thoughts (well, third, probably…) about doing it this way, though.

Thanks for your help!
