### ISSUE TITLE
cache not invalidated with eg `use flake --impure`

### ISSUE THREAD

**Issue by cdmistman** [nix-community/nix-direnv#364]
in a repo where my `.envrc` contains only `use flake --impure`, I ran `nix flake update` but the `nix-direnv` cache wasn't invalidated. I'd argue this is surprising behavior, as nix commands without a specified path imply the cwd as the flake path. The cache invalidation occurs as-expected when i changed the line to be `use flake . --impure`.

**Comment by Mic92** [comment]
currently `--impure` is considered a file: https://github.com/nix-community/nix-direnv/blob/a7510c9073c9397d55e9336b72642fefb9dbd56c/direnvrc#L196
Not so sure if we should replicate nix's arg parser. Maybe there is a way to quickly filter flags out but than flags can also have arguments so it's tricky.

workaround that works today: `nix_direnv_watch_file flake.nix`

**Comment by bbenne10** [comment]
I have gone on record (and will now do so again) as saying that I think our argument parser is currently too clever by half, but I don't know a way to reduce the complexity without limiting use cases. I stand with the idea that we should not complicate the matter further.

I would happily accept a PR to clarify this in the README, but I don't think I'll support changing the arg parser further without serious justification.

**Comment by bbenne10** [comment]
Note that this should mostly be addressed by #372

**Comment by Mic92** [comment]
I think it does.
