### ISSUE TITLE
"nix-direnv: nix version is older than the required 2.4", but nix is 2.15

### ISSUE THREAD

**Issue by byrongibson** [nix-community/nix-direnv#370]
I just built a new nix 23.11 unstable derivation and installed direnv and nix-direnv using `programs.direnv = {}` in configuration.nix.  When I reboot and cd into a previously existing direnv directory, I now get the following error:

```
> cd dev/web/proj01/src/ 
direnv: loading ~/dev/web/proj01/src/.envrc
direnv: using nix
/home/bgibson/.config/direnv/direnvrc:28: /nix/store/q6r9kwmidiy6wx1w1nf3ff0q40sfq4dg-nix-2.15.1/bin/nix: No such file or directory
direnv: nix-direnv: nix version  is older than the required 2.4.
direnv: error exit status 1

> nix --version
nix (Nix) 2.15.1

> direnv --version
2.32.3

> ls .config/direnv/        
Permissions Links Size User    Group Date Modified    Name
.r-xr-xr-x      1  11k bgibson users 2023-07-27 11:38 direnvrc*

> ls /nix/store/q6r9kwmidiy6wx1w1nf3ff0q40sfq4dg-nix-2.15.1/
"/nix/store/q6r9kwmidiy6wx1w1nf3ff0q40sfq4dg-nix-2.15.1/": No such file or directory (os error 2)

> ls /nix/store|grep nix-2.15
dr-xr-xr-x      3     - root root  1969-12-31 16:00 3hrx03ciy8zbgwj3p2jgsbc798rzg93y-nix-2.15.1-man/
dr-xr-xr-x      5     - root root  1969-12-31 16:00 rkm02xvbxb68d1kn2bj33xwva9pff0dc-nix-2.15.1-dev/
dr-xr-xr-x      3     - root root  1969-12-31 16:00 wsjy168bs2w1zl7d72n6h1lr36rz4c1m-nix-2.15.1-doc/
dr-xr-xr-x      7     - root root  1969-12-31 16:00 ywlpcc5zikgjhgcv09avzyz7p1sd0f3b-nix-2.15.1/
.r--r--r--      2  7.3k root root  1969-12-31 16:00 p02fb3jgh8kknaz2na2w3b7rzaxhd3ph-nix-2.15.1.drv

> ls /nix/store/ywlpcc5zikgjhgcv09avzyz7p1sd0f3b-nix-2.15.1/
Permissions Links Size User Group Date Modified    Name
dr-xr-xr-x      2    - root root  1969-12-31 16:00 bin/
dr-xr-xr-x      4    - root root  1969-12-31 16:00 etc/
dr-xr-xr-x      4    - root root  1969-12-31 16:00 lib/
dr-xr-xr-x      3    - root root  1969-12-31 16:00 libexec/
dr-xr-xr-x      5    - root root  1969-12-31 16:00 share/

```

Seems direnv is finding a different version of nix-2.15.1 with a different hash than the one currently installed.  Maybe it's hardcoded a reference to an old nix derivation that's since been replaced and garbage-collected?  Any idea why it's not finding the current nix path?

(Fwiw this issue is similar to #229 and #208 but neither solution seems applicable here.)

**Comment by byrongibson** [comment]
Fixed by editing the hardcoded path to nix at the top of `~/.config/direnv/direnvrc`, updated to current nix hash and path.  I guess for future nixos rebuilds, I should just delete this file and let direnv regenerate it?

**Comment by bbenne10** [comment]
...I'm not convinced that this is a problem we caused. 

We don't manage `~/.config/direnv/direnvrc` at all. The only thing we do is provide a file that needs to be sourced *from* `~/.config/direnv/direnvrc`. I suspect there might be a problem with the manner in which `~/.config/direnv/direnvrc` is built (home-manager, I guess?), but I can't tell for sure without more information regarding your setup.

**Comment by byrongibson** [comment]
Not using home-manager, just a monolithic configuration.nix.  It is flakes-enabled, but not using flakes anywhere yet either.

Here's the section at the top of `~.config/direnv/direnvrc` that was causing the problem:

```
# shellcheck shell=bash
NIX_BIN_PREFIX=/nix/store/ywlpcc5zikgjhgcv09avzyz7p1sd0f3b-nix-2.15.1/bin/

REQUIRED_DIRENV_VERSION="2.21.3"
```

That NIX_BIN_PREFIX line isn't in your direnv, and I didn't add it to mine.  Any idea how it got there?

**Comment by bbenne10** [comment]
If you're not using home-manager, what is putting `~/.config/direnv/direnvrc` in place?
That should answer your question as to why that line is there.
I went looking at your repos hoping something was public that I could inspect but I couldn't find a relevant repository (the only nixfiles repo seems to be a 2 year out-of-date fork and thus probably not what I wanted to look at).

I also went and looked at the unstable nix support for direnv and it does not look like it sets these values for users either. 
I'm not sure where these are coming from, but I can say that nix-direnv itself is not it. 
Can you share you configuration? At least the part that sets up direnv and nix-direnv?

**Comment by byrongibson** [comment]
Ah, I manually downloaded direnvrc from your repo and put it in ~/.config/direnv/direnvrc.  I didn't add that that NIX_BIN_PREFIX line to it though.

However, it seems I may have misread your instructions under the "Installation via system configuration on NixOS" section though:

```
# put this in ~/.config/direnv/direnvrc
source /run/current-system/sw/share/nix-direnv/direnvrc
```

I just copied the whole direnvrc file into that .config directory, instead of just one-line file with the command to source it from /run/current.../direnvrc.  However, that source target doesn't exist on my installation:

```
> less /run/current-system/sw/share/nix-direnv/direnvrc
/run/current-system/sw/share/nix-direnv/direnvrc: No such file or directory

> direnv --version 
2.32.3

> ls -al /run/current-system/sw/share/nix-direnv
Permissions Size User Group Date Modified    Name
dr-xr-xr-x     - root root  1969-12-31 16:00 ./
dr-xr-xr-x     - root root  1969-12-31 16:00 ../

> cd dev/web/test/      
direnv: loading ~/dev/web/test/.envrc
direnv: using nix
direnv: nix-direnv: using cached dev shell
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +DENO_BIN +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_LDFLAGS +NIX_STORE +NM +NODE_BIN +NODE_PATH +OBJCOPY +OBJDUMP +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +__structuredAttrs +buildInputs +buildPhase +builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +mesonFlags +name +nativeBuildInputs +out +outputs +patches +phases +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH ~XDG_DATA_DIRS
```

I'll upload my configuration.nix shortly.

**Comment by bbenne10** [comment]
Did you also add the rest of the configuration listed there to your nixOS config?

```nix
environment.systemPackages = with pkgs; [ direnv nix-direnv ];
  # nix options for derivations to persist garbage collection
  nix.settings = {
    keep-outputs = true;
    keep-derivations = true;
  };
  environment.pathsToLink = [
    "/share/nix-direnv"
  ];
```

This adds nix-direnv to `systemPackages` and sets up garbage collection persistence. This should create  `/run/current-system/sw/share/nix-direnv/direnvrc`.

**Comment by byrongibson** [comment]
Yes, here is all of my direnv/nix-direnv related config.  The only difference is I'm using `programs.direnv = {...}` instead of putting direnv and nix-direnv in `environment.systemPackages = [...];

```
# direnv config
nix.settings = {
  keep-outputs = true;
  keep-derivations = true;
};

environment.pathsToLink = [ 
  "/share/zsh"
  "/share/nix-direnv"
];

programs.direnv = {
  enable = true;
  package = pkgs.direnv;
  silent = false;
  persistDerivations = true;
  loadInNixShell = true;
  direnvrcExtra = "";
  nix-direnv = {
    enable = true;
    package = pkgs.nix-direnv;
  };
```

**Comment by byrongibson** [comment]
Fwiw you don't have spend any more time on this if you have other things to do.  It all works perfectly now, the problem isn't occurring anymore, and I can't reproduce it.  I don't know how that odd line got into direnvrc, but it seems fixed now.

**Comment by bbenne10** [comment]
Given that there's some churn happening right now upstream (with the addition of `programs.direnv` and the like), I'm going to say "Ghosts did it! Hopefully they don't do it again! But if they do - open an issue and reference this one, please" while I close this. I'm glad it is sorted for you.
