### ISSUE TITLE
Can't get `read -e -i` to work with nix-direnv

### ISSUE THREAD

**Issue by blaix** [nix-community/nix-direnv#384]
When I enter a directory with a `shell.nix` and `use nix` in `.envrc` and `nix-direnv.enable = true;` enabled in home manager, `read -e -i text` acts like `read -e` in bash scripts. For example:

```bash
❯ cat -p .envrc
use nix
❯ cat -p shell.nix
with import <nixpkgs> {};
mkShell {
  buildInputs = [
  ];
}
❯ cat -p test.sh
#!/usr/bin/env bash

read -e -i "text" input
echo $input
```

With normal direnv + use nix:

```bash
❯ ./test.sh
text
text
❯ 
```

With nix-direnv + use nix:

```bash
❯ ./test.sh


❯ 
```

I am on an m1 mac with macos 13.5, nix-darwin, and zsh 5.9.

**Comment by Mic92** [comment]
This is more an issue of mkShell bringen bash without readline support into $PATH

This should fix your issue:

```
with import <nixpkgs> {};
mkShell {
  buildInputs = [ bashInteractive ];
}
```

**Comment by blaix** [comment]
Yep, that fixes it. Thanks!

Is that the readline issue described in https://github.com/NixOS/nix/issues/4299 ?

**Comment by blaix** [comment]
...and I guess https://github.com/NixOS/nixpkgs/issues/59209

Sounds like I've run into a common problem 😅

**Comment by Mic92** [comment]
Actually nix-shell doesn't cause this

```
 nix-shell -p hello
this path will be fetched (0.05 MiB download, 0.22 MiB unpacked):
  /nix/store/wv3s1jl5p71fy9ip4lnhjvbmfbmkmjx2-hello-2.12.1
copying path '/nix/store/wv3s1jl5p71fy9ip4lnhjvbmfbmkmjx2-hello-2.12.1' from 'https://cache.nixos.org'...

[nix-shell:/tmp/distracted-brattain-0ovW5J]$ which bash
/nix/store/anvg6mpa8q2lvhp1h0yr3yn960zskrfj-bash-interactive-5.2-p15/bin/bash
```

It's really stdenv.mkDerivation from nixpkgs. That's why I always put bashInteractive into my shells with this template: https://github.com/Mic92/flake-templates/blob/main/nix-shell/default.nix
