### ISSUE TITLE
Please make a new release

### ISSUE THREAD

**Issue by lilyball** [nix-community/nix-direnv#387]
I really want to use `nix_direnv_manual_reload` (#359) but you haven't put out a release since April. Can you please make a new release (and then update it in nixpkgs)?

**Comment by bbenne10** [comment]
Request for a release is noted, but I would like to resolve #386 before we push a new release upstream to nixpkgs. 
In the meantie, there are many ways to install nix-direnv. 
Maybe one of the other options would work for you?
If not - you could pretty easily update the derivation in an overlay (or a local derivation).

**Comment by Mic92** [comment]
https://github.com/nix-community/nix-direnv/releases/tag/2.4.0
