### ISSUE TITLE
nix-direnv 2.4.0 hangs when using existing cache

### ISSUE THREAD

**Issue by PetarKirov** [nix-community/nix-direnv#396]
Since upgrading to nix-direnv 2.4.0 (from 2.2.1 in several projects, and 2.3.0 in others) nix-direnv started hanging in case there's an existing cache.

<details><summary><code>.envrc</code> </summary>

```sh
# shellcheck shell=bash
if ! has nix_direnv_version || ! nix_direnv_version 2.4.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.4.0/direnvrc" "sha256-XQzUAvL6pysIJnRJyR7uVpmUSZfc7LSgWQwq/4mBr1U="
fi

dotenv_if_exists
nix_direnv_watch_file shell.nix
use flake
```
</details>

Logs:
```
direnv: loading ~/project/.envrc
direnv: loading https://raw.githubusercontent.com/nix-community/nix-direnv/2.4.0/direnvrc (sha256-XQzUAvL6pysIJnRJyR7uVpmUSZfc7LSgWQwq/4mBr1U=)
direnv: using flake
direnv: nix-direnv: using cached dev shell
[ several minutes later and Ctrl-C ]
direnv: error signal: killed
```

If I clear the cache like this: `rm -rf .direnv`, nix-direnv successfully loads the shell in about < 0.5 secs (as was usually the case before).

```
> rm -rf .direnv
direnv: loading ~/project/.envrc
direnv: loading https://raw.githubusercontent.com/nix-community/nix-direnv/2.4.0/direnvrc (sha256-XQzUAvL6pysIJnRJyR7uVpmUSZfc7LSgWQwq/4mBr1U=)
direnv: using flake
direnv: nix-direnv: renewed cache
[ shellHook printed successfully ]
> [prompt ready]
```

Now, if I exit the environment and enter again, the problem reappears:

```
> pushd ..
> popd
direnv: loading ~/project/.envrc
direnv: loading https://raw.githubusercontent.com/nix-community/nix-direnv/2.4.0/direnvrc (sha256-XQzUAvL6pysIJnRJyR7uVpmUSZfc7LSgWQwq/4mBr1U=)
direnv: using flake
direnv: nix-direnv: using cached dev shell
[ nix-direnv hangs indefinitely ]
```

Running `nix develop` inside the same project is near instantaneous.

**Comment by bbenne10** [comment]
I just upgraded to unstable to hopefully be able to debug this issue easily, but ended up again with 2.3.0...

I'll replicate via source_url and report back with what I find. Sorry for the delay.

**Comment by PetarKirov** [comment]
Sorry for the noise, I figured out the problem. In our `mkShell` `shellHook` script with had the following line:

```
figlet -w$COLUMNS "${flake.description}"
```

When loading the shell for the first time, the `COLUMNS` env variable is set as expected, however when nix-direnv uses the cached shell the variable is not set and so the call to figlet became:

```
figet -w "Some message"
```

instead of say:

```
figlet -w120 "Some message"
```
 
and in the case of `figet -w "Some message"`, `Some message` was  interpreted as a parameter to the output width option (`-w`), which turn meant that figlet started waiting for input from stdin, which of course never comes since nix-direnv executes the dev shell in a non-interactive sub-shell.

**Comment by PetarKirov** [comment]
Note for others using `figlet`, a better way is to use the `-t` [option](http://www.figlet.org/figlet-man.html):
```
figet -t "Some message"
```

**Comment by PetarKirov** [comment]
Btw there is related problem cause by nix-direnv, which does not appear when using `nix develop` directly:

If the `flake.nix` has the `nixConfig.extra-{substituters,trusted-public-keys}` options set, and the user has not yet trusted these settings, `nix develop` hangs waiting for interactive input from the user:

```
➤ direnv allow .                                                                                                                                                                                                                                                                                   19:55:46 2023-10-25 (Wed)
direnv: loading ~/project/.envrc
direnv: loading https://raw.githubusercontent.com/nix-community/nix-direnv/2.4.0/direnvrc (sha256-XQzUAvL6pysIJnRJyR7uVpmUSZfc7LSgWQwq/4mBr1U=)
direnv: using flake
do you want to allow configuration setting 'extra-substituters' to be set to 'https://some-cache.cachix.org' (y/N)?
[ you can't answer "y" or "n" here]
```

**Comment by bbenne10** [comment]
Please open a new ticket as this is a fundamentally different issue. I am unsure how to resolve it as of yet, but we can discuss in a dedicated thread.
