### ISSUE TITLE
Update install instructions for nix-shell

### ISSUE THREAD

**Issue by jaredramirez** [nix-community/nix-direnv#40]
Hey, to get this package working by installing from nix-shell, I had to changed my `$HOME/.direnvrc` to
```
source $HOME/.nix-profile/share/nix-direnv/direnvrc
```

I think this would be helpful to add to the README in the nix-shell area. If you agree, I can submit a PR

**Comment by Mic92** [comment]
I clarified this now a bit more: https://github.com/nix-community/nix-direnv#with-nix-env

**Comment by Mic92** [comment]
Before it was not mentioned in every installation variant.

**Comment by Mic92** [comment]
If it is still not clear, feel to improve it further.
