### ISSUE TITLE
GC Roots inside of NixOS container

### ISSUE THREAD

**Issue by farnoy** [nix-community/nix-direnv#406]
I'm using NixOS containers and sharing the same home-manager setup on the host as well as inside of the container - meaning I have nix-direnv working the same way.

Flakes on the host get properly pinned with gc roots, which works flawlessly. For flakes inside of a container though, it's creating references that the nix daemon (?) cannot resolve and thinks they're stale, effectively ignoring & removing them later.

So, when I print the GC roots after evaluating a flake with nix-direnv, I see something like this:
```sh
$ nix-store --gc --print-roots
removing stale link from '/nix/var/nix/gcroots/auto/az1wdpfrx1xysnf1f42a6w18qjrj5537' to '/home/container-user/some-flake/.direnv/flake-profile.2157-1-link'
removing stale link from '/nix/var/nix/gcroots/auto/xm55fi1v3lgw7rq4xqiyx63m65am9lpx' to '/home/container-user/some-flake/.direnv/flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa'
removing stale link from '/nix/var/nix/gcroots/auto/5lqkd1fskkxsmlz85h1jhvcfq94qjs1a' to '/home/container-user/some-flake/.direnv/flake-inputs/yj1wxm9hh8610iyzqnz75kvs6xl8j3my-source'
removing stale link from '/nix/var/nix/gcroots/auto/m755gadkizz4b2j8x1vd8kv0k0asl9xq' to '/home/container-user/some-flake/.direnv/flake-inputs/4w4b4mxfhdc9lf3rsf4qqa9z8xnijbxl-source'
removing stale link from '/nix/var/nix/gcroots/auto/nk0s8dgja44m3wapmhahy4md5czy1qyh' to '/home/container-user/some-flake/.direnv/flake-inputs/9m34nhchq3wyjmpvg0gvjnbnq5bg3m8s-source'
removing stale link from '/nix/var/nix/gcroots/auto/cpxkbq2xbldfp34vmiyybxv5yz3rqmrf' to '/home/container-user/some-flake/.direnv/flake-inputs/g1vni6j5zxsx9w2965glrxifhiwgmfvn-source'
```

I'm pretty sure this happens because the paths are not valid if seen from the host fs namespace. `/home/container-user` in the container corresponds to `/var/lib/nixos-containers/container-name/home/container-user` in my case.

I don't think nix-direnv can or should detect this, but it would be good to be able to set a prefix for nix-direnv to use when creating these gcroot symlinks.

**Comment by Mic92** [comment]
Does nix itself also suffer from this problem or does it has a way around this issue?

**Comment by farnoy** [comment]
I checked with `nix build .` and it does suffer from the same problem.

There's also `/nix/var/nix/gcroots/per-container/container-name/` which gets mounted as `/nix/var/nix/gcroots` inside of the container. I'm not really sure how it's supposed to work. The nix-daemon runs on the host system, so who's supposed to be translating the scope of a container?

Should I submit this issue elsewhere?

**Comment by Mic92** [comment]
Intuitively I'd say that nix would to need to solve this issue.

**Comment by Mic92** [comment]
Some hack could be to rewrite gcroots prior to nix garbage collection?

**Comment by kjeremy** [comment]
I really need something like this too. I build on docker container's using gitlab-ci but use the host's daemon to do the actual building. I think #7138 could be an alternative solution to this if ever implemented.

**Comment by bbenne10** [comment]
If `nix build .` suffers the same problem, I don't know what we can do here? I see that it is a problem, but I just don't think *this layer* is where we fix it. I'll advocate for closing in preference to nixos/nix#7138

**Comment by Mic92** [comment]
Agreed. It's something that should be fixed at the source since nixos container is broken otherwise.
