### ISSUE TITLE
`nix_direnv_watch_file` should be `watch_file`

### ISSUE THREAD

**Issue by infinisil** [nix-community/nix-direnv#408]
If you want to make sure your environment is both automatically updated when files change, and updated to the correct value, and you don't know if the user has `nix-direnv` installed, you need to do something like this:

```bash
if has nix_direnv_watch_file; then
  nix_direnv_watch_file file.nix
else
  watch_file file.nix
fi

use nix
```

It would be much nicer if `nix-direnv` provided its own version of `watch_file` instead, such that a simple `watch_file file.nix` works.

`nix-direnv` would then also have the correct behavior by default for projects whose .envrc doesn't do anything special for nix-direnv.

**Comment by Mic92** [comment]
What if make `nix_watches+=()` the api? This will work also if you don't have nix-direnv.

**Comment by infinisil** [comment]
As far as I can see, there's never a case where you'd want to `watch_file` but not `nix_direnv_watch_file`, so overriding it would be fine.

Using `nix_watches+=()` would still require repos that were just considering `direnv` to make adjustments for `nix-direnv`.

**Comment by Mic92** [comment]
@zimbatm I guess there is no other api to check if a file is beeing watched by direnv?

**Comment by bbenne10** [comment]
@zimbatm has asked that we avoid monkey patching the direnv stdlib. 

However, I see no reason you couldn't do this:

```bash
if has nix_direnv_watch_file; then
  alias wf=nix_direnv_watch_file
else
  alias wf=watch_file
fi

wf flake.nix
```

**Comment by infinisil** [comment]
The problem with any approach that doesn't just use `watch_file` is that it requires all projects using `direnv` to explicitly add support for `nix-direnv` as above, and otherwise their caching is just broken for all `nix-direnv` users.

**Comment by bbenne10** [comment]
This is true. At work, we've taken the approach that using or not using `nix-direnv` is a *project* specification, which makes this a decision that we don't allow non-principal developers to override (Of course, they can discuss and influence direction, but we commit our `.envrc` to git to keep it consistent). We then use `source_url` to pin to a revision.

Yes - I agree that this is a bit frustrating. But the fact that both `direnv` and `nix-direnv` provide somewhat matching interfaces is a bit of an implementation detail in my eyes (and honestly - one I wish I could undo at this point. The confusion between the two projects has come up repeatedly in issues. I'd much prefer `use_flake_cache` or something...)

**Comment by infinisil** [comment]
Tbh `nix-direnv` should either just be built into `direnv` directly, or be some sort of plugin for it.

**Comment by Mic92** [comment]
You can use it as a plugin. Just add this to your project:

```
if ! has nix_direnv_version || ! nix_direnv_version 2.4.0; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.4.0/direnvrc" "sha256-XQzUAvL6pysIJnRJyR7uVpmUSZfc7LSgWQwq/4mBr1U="
fi
```

**Comment by Mic92** [comment]
Using a different name would have been also an annoyance, when a project comes with an .envrc that just uses `use nix` and everything gets slow again.
