### ISSUE TITLE
fallback to previous working env if building new env with changes fails

### ISSUE THREAD

**Issue by robert-elles** [nix-community/nix-direnv#412]
Hi,

when I make changes to my environment and they fail to build direnv just looses the whole environment. This is often unhelpful for the ongoing development work to fix the changes. It would be better if the previous environment stays active and can also be activated in a new terminal until the switch can be made.

Thank you and kind regards

**Comment by robert-elles** [comment]
FYI: I am using flakes

**Comment by bbenne10** [comment]
I think that #420 should resolve this. Can you test with latest master and report back if the experience is what you want and expect? Thanks!
