### ISSUE TITLE
does nix-direnv have good integration support for text editors, like emacs ?

### ISSUE THREAD

**Issue by zeta-00** [nix-community/nix-direnv#43]
Hello There,

I'm currently using lorri, which i'm really happy with for the most part, but I just recently heard about this nix-direnv alternative tool, while reading a nixos reddit forum. nix-direnv looks simpler and easier to setup and configure, than lorri, and nix-direnv being maintained by the nix-community is a huge plus. anyways, before I try nix-direnv, I want to know if it has good support for functionality, such as, integrating with a text editor, like emacs ? lorri has a lot of documentation for things like this, but nix-direnv currently does not, so I want to make sure that switching from lorri to nix-direnv will be a smooth transition.

I'm a little confused, so if you could clarify this, thanks in advance for the help !

**Comment by Mic92** [comment]
You can use the same direnv plugins for vim/emacs. However unlike lorri, nix-direnv is not asynchronous, so depending on you plugin it might block your editor if things needs to be downloaded: https://github.com/purcell/envrc/issues/6

**Comment by Mic92** [comment]
Does this answer your question?
