### ISSUE TITLE
direnv feature parity

### ISSUE THREAD

**Issue by blaggacao** [nix-community/nix-direnv#44]
Using _direnv_ proper, the `motd` of `numtide/devshell` is properly shown.
Using nix-direnv, it's not.

----

- Failing branch: https://github.com/numtide/devshell/pull/38
- Working branch : https://github.com/numtide/devshell/pull/39

----

In general it seems that any echo from the shellHook is swallowed.

**Comment by Mic92** [comment]
fixed in https://github.com/nix-community/nix-direnv/pull/46/commits/1ef31ac5ffcaca7dfc167e7bbbdd957612d9c708

**Comment by blaggacao** [comment]
Nice! Thank you I was trying to fix this myself but ultimately failed 😄

**Comment by blaggacao** [comment]
Unfortunately it looks like it doesn't work as intended.
![image](https://user-images.githubusercontent.com/7548295/96168659-af39cd80-0ee6-11eb-96bb-087f4bc7e64c.png)

vs without the `nix-direnv` (normal `direnv`):

![image](https://user-images.githubusercontent.com/7548295/96168752-d8f2f480-0ee6-11eb-8493-2b7bd7c248e6.png)

**Comment by Mic92** [comment]
Are you sure you updated it?

```
source /home/joerg/git/nix-direnv/direnvrc
use nix
```

```
with import <nixpkgs> {};
mkShell {
  nativeBuildInputs = [
    bashInteractive
  ];
  shellHook = ''
    echo foo
  '';
}
```

```
$ direnv allow
direnv: loading /tmp/tmp.sLD8ywsllI/.envrc
direnv: using nix
foo
direnv: eval /tmp/tmp.sLD8ywsllI/.direnv/cache-.git.3a3da0950d5
direnv: renewed cache and derivation link
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_STORE +NM +OBJCOPY +OBJDUMP +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +TEMP +TMP +TMPDIR +__ETC_PROFILE_SOURCED +buildInputs +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +name +nativeBuildInputs +nobuildPhase +out +outputs +patches +phases +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH
```
