### ISSUE TITLE
nix-direnv fails to correctly recognize bash version

### ISSUE THREAD

**Issue by sobornostea** [nix-community/nix-direnv#440]
Hello,

After upgrading my system, I get the following error when entering a previously functioning environment

```
direnv: loading ~/Repositories/myfolder
direnv: using flake
sort: Unknown option 'check=quiet' (see "sort --help")
direnv: nix-direnv: minimum required bash version is 5.2 (installed: 5.2.21(1)-release)
direnv: error exit status 1
```

This is  a valid version, but direnv fails to parse it as valid

The code responsible for this is :

```bash
_require_version() {
  local cmd=$1 version=$2 required=$3
  if ! printf "%s\n" "$required" "$version" | sort --check=quiet --version-sort; then
    _nix_direnv_fatal "minimum required $cmd version is $required (installed: $version)"
  fi
}

```
For some reason `sort` doesn't recognize the full form options (`--check=quiet --version-sort`), using the short form options (`-C -V`) does not fix the problem

If I look into using sort to sort `5.2` and `5.2.21(1)-release` it seems like the sorting is correct ? I don't understand how this error happens

Best,

**Comment by Mic92** [comment]
cc @kingarrrt

**Comment by Mic92** [comment]
What sort implementation are you using?

**Comment by kingarrrt** [comment]
Please provide output of:

```sh
uname -a
command -v sort
sort --version
man sort
```

**Comment by sobornostea** [comment]
Oh I think it comes from the `toybox` package (that I installed for some commands that weren't present by default)

Here is the output of the commands :

```
Linux oblast 6.6.6 #1-NixOS SMP PREEMPT_DYNAMIC Mon Dec 11 09:40:17 UTC 2023 x86_64 Toybox
/etc/profiles/per-user/sobornost/bin/sort
toybox 0.8.10
```

For the manpage : https://gist.github.com/sobornostea/98fbe651c4d36a0b4a039d0174537a6f (yeah, it looks copied from gnu core utils so the wrong one)

Seems like it's the wrong one, removing `toybox` fixes the issue (I don't understand why `toybox` suddenly had this behaviour, but I guess it's a bug for their upstream not yours, i'll bissect my NixOS configuration to double-check that it's a regression on their side and report to them)

Thank you very much for your time
