### ISSUE TITLE
nix-direnv: minimum required bash version is 5.2 

### ISSUE THREAD

**Issue by francis2tm** [nix-community/nix-direnv#448]
Hello,
I'm on Ubuntu 22.04

## Error

```
direnv: nix-direnv: minimum required bash version is 5.2 (installed: 5.1.16(1)-release)
```
And unfortunately, I cannot use nix-direnv since ubuntu's newest bash version is still 5.1.16. (and forcing a new version will probably kill my system)
Tried to use zsh instead, but apparently nix-direnv does not support any other shell than bash.

Any workaround that allows nix-direnv to become more flexible with the bash version?

Thanks

**Comment by bbenne10** [comment]
Install bash from nixpkgs into your profile. You can do this in any number of ways (`nix-env`, home-manager, etc)

**Comment by Mic92** [comment]
@kingarrrt do we actually need bash 5.2? Ubuntu 22.04 doesn't sound that old to me.

**Comment by kingarrrt** [comment]
> @kingarrrt do we actually need bash 5.2? Ubuntu 22.04 doesn't sound that old to me.

We don't. Per https://github.com/nix-community/nix-direnv/pull/429#issuecomment-1834305543 it could be bash 4. We chose bash 5.2 based on what's available in nixpkgs and homebrew.

@francis2tm Can you explain how you installed direnv and how you are using nix-direnv?

**Comment by Mic92** [comment]
Ok. I think we maybe should set it back to bash 4 than. Those versions are still in the latest redhat/centos versions AFAIK.

**Comment by francis2tm** [comment]
> > @kingarrrt do we actually need bash 5.2? Ubuntu 22.04 doesn't sound that old to me.
> 
> We don't. Per [#429 (comment)](https://github.com/nix-community/nix-direnv/pull/429#issuecomment-1834305543) it could be bash 4. We chose bash 5.2 based on what's available in nixpkgs and homebrew.
> 
> @francis2tm Can you explain how you installed direnv and how you are using nix-direnv?

Of course! Essentially my objective is to enable nix flake with vscode, specially extensions (e.g. I want rust-analyzer extension to use flake's rust toolchain).
So, after a lot of research, it seems direnv can kickstart nix flake using a mix of direnv + a [direnv extension](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-direnv) + nix-direnv

I installed direnv using ubuntu's package manager:
```
sudo apt install direnv
```

**Comment by Lyndeno** [comment]
This output confuses me:
```console
direnv: loading ~/Projects/nix-config/.envrc
direnv: using flake
sort: unrecognized option '--check=quiet'
BusyBox v1.36.1 () multi-call binary.

Usage: sort [-nrughMcszbdfiokt] [-o FILE] [-k START[.OFS][OPTS][,END[.OFS][OPTS]] [-t CHAR] [FILE]...

Sort lines of text

	-o FILE	Output to FILE
	-c	Check whether input is sorted
	-b	Ignore leading blanks
	-f	Ignore case
	-i	Ignore unprintable characters
	-d	Dictionary order (blank or alphanumeric only)
	-n	Sort numbers
	-g	General numerical sort
	-h	Sort human readable numbers (2K 1G)
	-M	Sort month
	-V	Sort version
	-t CHAR	Field separator
	-k N[,M] Sort by Nth field
	-r	Reverse sort order
	-s	Stable (don't sort ties alphabetically)
	-u	Suppress duplicate lines
	-z	NUL terminated input and output
direnv: nix-direnv: minimum required bash version is 5.2 (installed: 5.2.21(1)-release)
direnv: error exit status 1
```

I am on NixOS 24.05.20231211.a9bf124

**Comment by Mic92** [comment]
Ok. Now it's bash 4.4. I also further improved busybox compatibility: https://github.com/nix-community/nix-direnv/pull/455/commits/ced8704eff001cb6982baa6d175b1097b199abfb

**Comment by francis2tm** [comment]
@Mic92 Thanks!
