### ISSUE TITLE
Expose the invoking shell when using use nix

### ISSUE THREAD

**Issue by blaggacao** [nix-community/nix-direnv#45]
I'm also opening an issue here, since this implementation does not differ in this regard.

https://github.com/direnv/direnv/issues/691

**Comment by blaggacao** [comment]
Nice thank you! I'm going to test this soonish.

**Comment by Mic92** [comment]
You need to make the comparison with SHELL in direnvrc not in shell.nix, since nix will always set SHELL to bash.

**Comment by blaggacao** [comment]
Oh, thank you. Noted. I think in numtide/devshell context, we also need a solution for that, will be discussing it there. Thx!
