### ISSUE TITLE
Installing packages raises an "unknown setting 'upgrade-nix-store-path-url'" warning

### ISSUE THREAD

**Issue by zimeg** [nix-community/nix-direnv#466]
Hello! I've been diving into Nix recently and am wonderfully impressed with this package! Super excited to be using it 😄

When installing new packages from a flake the following warning appears and I'm unsure if this is caused by my Nix or home manager setup or the flake itself:

```sh
warning: unknown setting 'upgrade-nix-store-path-url'
```

This happens the first time I allow `direnv` in a directory and might happen multiple times after adding new packages.

<details>
<summary>Here's an example `flake.nix` that's causing this</summary>

```nix
{
  description = "A basic flake with a shell";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = { nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells.default = pkgs.mkShell {
          packages = [
            pkgs.bashInteractive
            pkgs.hello
          ];
        };
      });
}
```

</details>

This same warning isn't shown when using `nix-shell -p hello` and I'm not sure if this is due to my `nix-direnv` setup. Any pointers would be appreciated!

**Comment by zimeg** [comment]
I've poked around the repo a bit looking for hints and these lines seem most interesting for this: https://github.com/nix-community/nix-direnv/blob/e9076faefc13f95b2f621c48d726dd1b68cfe562/direnvrc#L311-L319

Finding the `flake_input_path` from my project directory outputs a few different paths, but I don't know if these are related to the unknown store path at all:

```sh
$ nix --extra-experimental-features "nix-command flakes" flake archive --json --no-write-lock-file .
{
  "inputs": {
    "flake-utils": {
      "inputs": {
        "systems": {
          "inputs": {},
          "path": "/nix/store/yj1wxm9hh8610iyzqnz75kvs6xl8j3my-source"
        }
      },
      "path": "/nix/store/qkig73szmrhgp0qhncxy5vb36lw2g3jj-source"
    },
    "nixpkgs": {
      "inputs": {},
      "path": "/nix/store/abh0p0f6fcqilmp3v24gfj00lp38wn6l-source"
    }
  },
  "path": "/nix/store/17lmjgndk0n510ld6xv4jq72y20r72bn-source"
}
```

**Comment by zimeg** [comment]
There's a related option for the `nix upgrade-nix` command too, but not sure if I can set this somewhere myself: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-upgrade-nix#opt-nix-store-paths-url

**Comment by bbenne10** [comment]
Of course, I hit "Comment" too soon. 
You may also want to just `set -x` at the top of your `.envrc` (before you call `use flake`) and see what nix invocations are complaining about this. I'm not *entirely* sure how this would help, but more information is better than less.

**Comment by zimeg** [comment]
@bbenne10 Really appreciate the response! There's so much helpful info here. I agree this does seem to be caused by something besides nix-direnv so no worries closing the issue. I'll keep exploring and will let you know if nix-direnv does seem to be causing it though.

Using the new CLI didn't seem to raise any warnings on install, which I think is good. It's also good to know about this command and that it installs flakes! There's still a lot for me to learn!

I think you're pointing down the right track with the contents of `nix.conf` and I'll follow this a bit more:

```
build-users-group = nixbld
experimental-features = nix-command flakes repl-flake
bash-prompt-prefix = (nix:$name)\040
max-jobs = auto
extra-nix-path = nixpkgs=flake:nixpkgs
upgrade-nix-store-path-url = https://install.determinate.systems/nix-upgrade/stable/universal
```

The version of Nix and the Nix installer I have are:

```sh
$ nix --version
nix (Nix) 2.19.2
$ /nix/nix-installer --version
nix-installer 0.16.0
```

And the versions listed in the `upgrade-nix-store-path-url` are:

```sh
{
  x86_64-linux = "/nix/store/smfmnz0ylx80wkbqbjibj7zcw4q668xp-nix-2.19.2";
  i686-linux = "/nix/store/knp0akbpj2k0rf26fmysmxdysmayihax-nix-2.19.2";
  aarch64-linux = "/nix/store/761hq0abn07nrydrf6mls61bscx2vz2i-nix-2.19.2";
  x86_64-darwin = "/nix/store/zlqvxis1dfcfgmy5fza4hllg6h03vhpb-nix-2.19.2";
  aarch64-darwin = "/nix/store/53r8ay20mygy2sifn7j2p8wjqlx2kxik-nix-2.19.2";
}
```

You're totally right that this is only a warning and everything does seem to be working fine, I was mostly curious if there was an obvious setting for me to switch. The `set -x` option is giving me a bit to read through so I'll read through that and explore the discourse some more too. Thank you!

**Comment by antoineco** [comment]
I've been thrown off by these messages at first as well, given that I am using the latest Nix version at the time of writing:

```console
$ /run/current-system/sw/bin/nix --version
nix (Nix) 2.24.6
```

In fact, the messages aren't that surprising once you figure that `nix-direnv`, when installed from nixpkgs, calls a `nix` executable at a hardcoded Nix store path (which makes sense in the context of nixpkgs):

```
/nix/store/cv2a6x2iq50n6w8rlz14ldfpfnqs5acy-nix-2.18.5/bin/nix
```

**Comment by Mic92** [comment]
> I've been thrown off by these messages at first as well, given that I am using the latest Nix version at the time of writing:
> 
> ```
> $ /run/current-system/sw/bin/nix --version
> nix (Nix) 2.24.6
> ```
> 
> In fact, the messages aren't that surprising once you figure that `nix-direnv`, when installed from nixpkgs, calls a `nix` executable at a hardcoded Nix store path (which [makes sense](https://github.com/NixOS/nixpkgs/blob/44a71ff39c182edaf25a7ace5c9454e7cba2c658/pkgs/by-name/ni/nix-direnv/package.nix#L31) in the context of nixpkgs):
> 
> ```
> /nix/store/cv2a6x2iq50n6w8rlz14ldfpfnqs5acy-nix-2.18.5/bin/nix
> ```

afaik it uses nix from $PATH now and does fallback to its hardcoded nix if it cannot find it: https://github.com/nix-community/nix-direnv/pull/513

**Comment by antoineco** [comment]
Thanks for the pointer! I'm using 3.0.5, the version currently packaged for NixOS 24.05. It's good to know that I don't have to override it moving on 🙂
