### ISSUE TITLE
How do I load environment vairibale in .env automatically?

### ISSUE THREAD

**Issue by ylbeethoven** [nix-community/nix-direnv#477]
Hi, 

This tool is great for loading `flake.nix` or `shell.nix` but it is not clear how it could work like the standard `direnv` which loads `.env` automatically.

When I tried `direnv allow`, I am getting.
```bash
error .envrc file not found
```

Do I have to use a `shell.nix` to load environment variable?

**Comment by bbenne10** [comment]
Just add the environment variable to your `mkShell` invocation. All non-recognized keys will be exported as environment variables.

**Comment by ylbeethoven** [comment]
> Just add the environment variable to your `mkShell` invocation. All non-recognized keys will be exported as environment variables.

Thanks for the reply.

I guess this confirms that this tool can not be used to load `.env` directly. 

Do you mind sharing an simple example?  I know below works but I am not too sure if it is the best way to do it.

```nix
# save this as shell.nix
{ pkgs ? import <nixpkgs> {}}:

pkgs.mkShell {
    shellHook = ''
      export VAR_NAME=abc
    '';
}
```
