### ISSUE TITLE
Better integration into package manager when loading third-party plugins

### ISSUE THREAD

**Issue by zimbatm** [nix-community/nix-direnv#5]
It would be great if `direnv` would have something like a .direnv.d or even environment variables to load third party plugins. I think it is time to package nix-direnv in nixpkgs itself.

_Originally posted by @Mic92 in https://github.com/nix-community/nix-direnv/issues/3#issuecomment-597553701_

**Comment by zimbatm** [comment]
@Mic92 direnv looks in ~/.config/direnv/lib/*.sh for additional libs. (since v2.21)

Like you said it doesn't play nicely with package managers but I am open to suggestions. I don't know how bad it would be to load arbitrary code from the system yet.

**Comment by zimbatm** [comment]
Another experiment I have is a new `source_url` stdlib function over here: https://github.com/direnv/direnv/pull/562

**Comment by Mic92** [comment]
For nix we would need a search path for full integration to load plugins from all possible user and system profiles.

something like: DIRENV_PLUGIN_PATH=$HOME/.nix-profile/lib/direnv/:/run/current-system/sw/lib/direnv:/nix/var/nix/profiles/default/lib/direnv

If not set direnv could fallback to a compiled-in PREFIX, i.e

DIRENV_PLUGIN_PATH=/usr/local/lib/direnv/

if PREFIX == /usr/local/

For other package manager is is usually fine to only lookup in `PREFIX`.

**Comment by Mic92** [comment]
Now nix-direnv is loaded from the nix-profile: https://github.com/nix-community/nix-direnv#home-manager

**Comment by Mic92** [comment]
I think I am fine with the status quo of using home-manager to load this.
