### ISSUE TITLE
Error in usage example

### ISSUE THREAD

**Issue by truh** [nix-community/nix-direnv#50]
There is an error in the usage example shell.nix file.
https://github.com/nix-community/nix-direnv#usage-example

With the current example I get:

```
error: syntax error, unexpected '}', expecting ';', at [...]/shell.nix:1:34
```

Removing the with statement solves the error.

**Comment by Mic92** [comment]
Fixed in https://github.com/nix-community/nix-direnv/blob/master/README.md
