### ISSUE TITLE
direnv does not apply --extra-experimental-features 'nix-command flakes' 

### ISSUE THREAD

**Issue by ThanePatrol** [nix-community/nix-direnv#509]
Direnv version: 2.34.0

per title, causes the flake to not be applied:

```sh
echo "use flake ~/nixos/#go_1_19" > .envrc && direnv allow
direnv: loading ~/nixos/.envrc
direnv: using flake /Users/hugh/nixos/#go_1_19
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```

If the flags are provided in the direnv command then the flake is applied:
```sh
echo "use flake --extra-experimental-features 'nix-command flakes' ~/nixos/#go_1_19" > .envrc && direnv allow
direnv: loading ~/nixos/.envrc
direnv: using flake --extra-experimental-features nix-command flakes /Users/hugh/nixos/#go_1_19
warning: Git tree '/Users/hugh/nixos' is dirty
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
# rest of the env variables being exported, etc
```
I can see the flake works as I get the correct versions of packages available but based upon previous issues https://github.com/nix-community/nix-direnv/issues/209 it seems like this should not be an issue

Defined in the outputs of my main flake.nix as 
```nix
        devShells.aarch64-darwin = {
          go_1_19 = 
          let pkgs = golang_1_19.legacyPackages.aarch64-darwin;
          in
          pkgs.mkShell {
            buildInputs = [ 
              pkgs.go_1_19
            ];
          };
        };
```
Full repo here: https://github.com/ThanePatrol/nixos

**Comment by bbenne10** [comment]
Can you re-run this after calling `set -x` in your `.envrc`? This will enable us to see which nix invocations aren't being handled right. 

The issue here is that I *think* that we're doing the "right" thing (all calls to the `nix` binary go through the `_nix` function, which adds `--extra-options "nix-command flakes"`, as far as I can see?)

**Comment by Mic92** [comment]
Can you add:

```
if ! has nix_direnv_version || ! nix_direnv_version 3.0.5; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.5/direnvrc" "sha256-RuwIS+QKFj/T9M2TFXScjBsLR6V3A17YVoEW/Q6AZ1w="
fi
```

before your code in .envrc? Does it fix this the issue? If yes, you are not using nix-direnv at the moment but the stock implementation that comes with direnv.

**Comment by bbenne10** [comment]
Wait - I don't think you're using nix-direnv at *all*, actually.

You've not enabled the nix service, which automatically enables nix-direnv in current versions (all you've done is add direnv to `systemPackages` and then call `direnv hook zsh` in `zsh.initExtra`, which isn't enough to *have nix-direnv around*). You'll need to either:

* use home-manager and their direnv integration
* use nixos and the system direnv integration
* manually add nix-direnv to your shell some other way

**Comment by bbenne10** [comment]
An aside: I do wonder if there's benefit in changing the names of our functions to *not* override the ones provided by direnv itself. It'd make triaging the most common issues (setup) MUCH MUCH easier.

**Comment by Mic92** [comment]
> An aside: I do wonder if there's benefit in changing the names of our functions to _not_ override the ones provided by direnv itself. It'd make triaging the most common issues (setup) MUCH MUCH easier.

Problem is that you than always have to explicitly add some source_url and many projects won't do that. I prefer convenience here over occasionally mis-configuraton. After all the direnv version is also working, it's just slower.

**Comment by Mic92** [comment]
And also we should just fix direnv to also enable flakes.

**Comment by Mic92** [comment]
Also it's way too late to do a rename. The whole ecosystem would break down over this change.

**Comment by Mic92** [comment]
https://github.com/direnv/direnv/pull/1299

**Comment by Mic92** [comment]
The thing is I always want to be able to use my `use_nix` function if someone is using it in a project. If we call our function something else, this will no longer work.
Here an example: https://github.com/NixOS/nixpkgs/blob/master/.envrc

If we call the function something else than people need to use:

```
if ! has nix_direnv_version || ! nix_direnv_version 3.0.5; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.5/direnvrc" "sha256-RuwIS+QKFj/T9M2TFXScjBsLR6V3A17YVoEW/Q6AZ1w="
fi
```

in all of the projects, which is something they could already to today without having to rename the function, if they want consistent results for everyone.

**Comment by Mic92** [comment]
> If the benefit of KEEPING the current name is that it works when nix direnv isnt installed, isnt it consistent to apply the same benefit to us renaming functions? The world would not break - it'd evaluate slower.

Yes, I don't want to be slower for me :)

**Comment by Mic92** [comment]
Direnv's stdlib now also enables these flags.

**Comment by ThanePatrol** [comment]
@Mic92 great catch! Thanks for the help :)

> Can you add:
> 
> ```
> if ! has nix_direnv_version || ! nix_direnv_version 3.0.5; then
>   source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/3.0.5/direnvrc" "sha256-RuwIS+QKFj/T9M2TFXScjBsLR6V3A17YVoEW/Q6AZ1w="
> fi
> ```
> 
> before your code in .envrc? Does it fix this the issue? If yes, you are not using nix-direnv at the moment but the stock implementation that comes with direnv.
