### ISSUE TITLE
security wrappers for cap_net_bind_service support

### ISSUE THREAD

**Issue by adminy** [nix-community/nix-direnv#518]
I was reading this great article on [extending programs with a security wrapper](http://vhsconnect.link/posts/2021-08-29-extending-node-with-security-wrapper-on-nix.html) and I thought this kind of binary wrapping should be possible with direnv also.

```nix
security.wrappers = {
  node = {
    source = "${pkgs.nodejs}/bin/node";
    capabilities = "cap_net_bind_service=+ep";
  };
  yarn = {
    source = "${pkgs.nodePackages.yarn}/bin/yarn";
    capabilities = "cap_net_bind_service=+ep";
  };
};
```

which apparently creates a symlink inside `/run/wrappers/bin` to be able to run programs with port <=1024 as a normal user.

I'm just not sure `mkShell` actually has anything besides `shellHook` to do this though.

**Comment by bbenne10** [comment]
As I understand it, `security.wrappers` is a *nixos* option, which means we don't directly have access to set it in a devShell. You'd need a system definition (flake or channel) with that option set. There's little we can do here, I expect.
