### ISSUE TITLE
nix-direnv doesn't fully rebuilt cache when sub flake changes

### ISSUE THREAD

**Issue by sezaru** [nix-community/nix-direnv#534]
Hello,

I have the following flakes:

`.flakes/postgresql/flake.nix`:
```nix
{
  description = "A shell flake for PostgreSQL";

  inputs = {
   ...
  };

  outputs =
    { nixpkgs, flake-utils, ... }@inputs:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        ...
      }
    );
}
```

`.flakes/elixir/flake.nix`:
```nix
{
  description = "A shell flake for Elixir";

  inputs = {
   ...
  };

  outputs =
    { nixpkgs, flake-utils, ... }@inputs:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        ...
      }
    );
}
```

I want to use both flakes in my env, since settings `use flake` twice would invalidate the cache of the first call, I created another flake that "merges" the flakes above:

`.flakes/flake.nix`:
```nix
{
  description = "A shell flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    systems.url = "github:nix-systems/default";
    flake-utils = {
      url = "github:numtide/flake-utils";
      inputs.systems.follows = "systems";
    };

    elixir-flake = {
      url = "path:./elixir";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        systems.follows = "systems";
        flake-utils.follows = "flake-utils";
      };
    };

    postgresql-flake = {
      url = "path:./postgresql";
      inputs = {
        nixpkgs.follows = "nixpkgs";
        systems.follows = "systems";
        flake-utils.follows = "flake-utils";
      };
    };
  };

  outputs =
    { nixpkgs, flake-utils, ... }@inputs:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
      in
      {
        devShells.default = pkgs.mkShell {
          inputsFrom = [
            inputs.elixir-flake.devShells.${system}.default
            inputs.postgresql-flake.devShells.${system}.default
          ];
        };
      }
    );
}
```

It basically adds both flakes to its inputs and then creates a new shell with them in the `inputsFrom` list.

Finally, I have this in my `.envrc`:

```
watch_file .flakes/elixir/flake.nix
watch_file .flakes/elixir/flake.lock

watch_file .flakes/postgresql/flake.nix
watch_file .flakes/postgresql/flake.lock

use flake .flakes
```

The issue is that if I change anything in the elixir or postgresql flakes, that change will not be seen by direnv and it will not trigger a rebuilt.

Even if I call `nix-direnv-reload`, it will, at most, only rebuild the root flake, it will never rebuild the elixir and postgresql again.

The only way to make the changes be applied that I found was to go inside the `.flakes` dir and run `nix flake update`.

Is there some way to make nix-direnv see the changes and rebuilt these flakes instead of just always reusing the cache?

**Comment by bbenne10** [comment]
Your `watch_file` for the subflake should do it...

Ill replicate this today and work on a strategy

**Comment by bbenne10** [comment]
Oh. The problem is that the `watch_file` invalidates the top level "meta-flake", which has a lock itself. You'll need tp work around locking in the flake infrastructure to fix this...does a `path` input work, maybe?

**Comment by sezaru** [comment]
Thanks for the quick reply @bbenne10 

Do you mind elaborating a little bit more on what you mean by a `path` input? I just started my Nix journey yesterday, so I'm still not too familiar with all its features.

**Comment by bbenne10** [comment]
You're already *using* them. I misread your post above... (they're the `path:...` input lines in your top-level flake)

Why are you doing this this way? I suspect there's something you're trying to achieve that you want to do with this sort of approach, but maybe there's a better way? (Without deeper knowledge, this feels like a job for [flake parts](https://flake.parts), but I don't know what you're doing).

This is, ultimately, a problem with flakes rather than a nix-direnv problem, I think...

**Comment by sezaru** [comment]
Basically all I'm trying to do is separated my flakes by scope so I can easily re-use them in other projects.

For example, in this case I have a flake to setup Elixir development, and also one to setup a PostgreSQL database. Since the project I'm using this is written in Elixir and it uses PostgreSQL as its db.

At the same time, I can have another project that is written in Go with PostgreSQL, in this case I want to just write a Go flake and copy/paste/reuse my PostgreSQL flake.

That is my main goal with this.

I will take a look at flake parts and see if I can rewrite my current setup with it. Thanks for the help so far :)

**Comment by bbenne10** [comment]
You probably want flake-parts for that. It has pretty much the same goal. It utilizes modules to this end. 

Generally, the nix ecosystem takes the approach that "if it is public enough for inter-project reuse, it should be hosted somewhere else - probably in a dedicated repo". This means it gets versioned appropriately and you can (and more importantly *must*) bump those versions consciously. This gets frustrating sometimes. I don't really have any more to say on that matter.

I generally find it good enough :tm: to copy and paste snippets from my other flakes. They compose pretty quickly and fail loudly. This means I don't really have these sorts of issues (but I do have other ones! So it isn't perfect :P)

**Comment by bbenne10** [comment]
If you find that this is, in fact, a problem inside nix-direnv, I will happily re-open this ticket.
