### ISSUE TITLE
TMP directory in nix shell does not exist

### ISSUE THREAD

**Issue by Noratrieb** [nix-community/nix-direnv#538]
I'm not sure if direnv is where the problem lies.

Reproduction steps:

Create any nix shell and use it with direnv. `$TMP`/`$TEMP` will be set to a path that does not exist.

shell.nix:
```nix
{ pkgs ? import <nixpkgs> { } }: pkgs.mkShell {
}
```
.envrc:
```sh
use nix
```

```sh
$ direnv allow
direnv: loading /tmp/tmp.YvJciMhTqa/.envrc
direnv: using nix
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_LDFLAGS +NIX_STORE +NM +OBJCOPY +OBJDUMP +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +TEMP +TEMPDIR +TMP +TMPDIR +__structuredAttrs +buildInputs +buildPhase +builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +mesonFlags +name +nativeBuildInputs +out +outputs +patches +phases +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH ~XDG_DATA_DIRS

$ echo $TMP
/tmp/nix-shell-105145-0
$ ls $TMP
ls: cannot access '/tmp/nix-shell-105145-0': No such file or directory
```

When entering the shell manually through `nix-shell` instead of direnv, `$TMP` is set to a similar value, but the directory *does* exist, which makes me think that the problem is related to direnv.

I am using NixOS unstable with nixpkgs commit d0797a04b81caeae77bcff10a9dde78bc17f5661. I don't remember when this started exactly, but it was a recent regression, happening within the last one or two months.

**Comment by Noratrieb** [comment]
ah no, this is the wrong direnv, sorry.

**Comment by bbenne10** [comment]
Can you expand on this "not being the right direnv"? How did you determine that? (I ask because nix-direnv is auto-enabled if you use `programs.direnv` on nixos).

**Comment by Noratrieb** [comment]
1) `direnv --version` showed a version number that's the latest one for the other direnv but doesn't exist here
2) there's an open issue with lots of comments over there

**Comment by bbenne10** [comment]
Is "The other one" [direnv/direnv? ](https://github.com/direnv/direnv)

If so, I expect you are confused.
This repository (nix-direnv) is a *plugin* for direnv, not a fork or competing project.

Is the other open issue this one? https://github.com/direnv/direnv/issues/1345 If so, I suspect we circumvent this by un-setting that environment variable preemptively.

**Comment by Noratrieb** [comment]
Yes, I meant that issue. Thanks for the response!
