### ISSUE TITLE
Built-in "use flake" used instead of nix-direnv on NixOS

### ISSUE THREAD

**Issue by cdfa** [nix-community/nix-direnv#539]
This is probably something really stupid, but `nix-direnv` is not enabled even though I have `config.programs.direnv.nix-direnv = true` (checked in a nix repl).

My `.envrc` contains `use flake ".?submodules=1#"`. I'm on nixpkgs `4633a7c72337ea8fd23a4f2ba3972865e3ec685d` (unstable from a few weeks back).

How should I debug?

**Comment by cdfa** [comment]
I checked with `nixos-rebuild repl`. I also have `config.programs.direnv.enabled = true;`.
I asked here because I thought debugging steps could be `nix-direnv` specific, but maybe I'm wrong.

I dug into the NixOS module and found that it sets a `DIRENV_CONFIG` variable, which was not set in my shell.
Apparently I had ` environment.variables = lib.mkForce { ... }` in my config for some reason, which caused all system environment variables except those defined in that record to be dropped.
I'm feel ashamed I didn't notice this from other things being broken on my system 😅

Sorry for bothering you haha

**Comment by bbenne10** [comment]
Thanks for reporting back and I am very glad you got it sorted!
