### ISSUE TITLE
`use flake` on macOS fails due to missing `realpath`

### ISSUE THREAD

**Issue by jamesottaway** [nix-community/nix-direnv#54]
I'm trying `nixUnstable` to tinker with flakes, and hence tried `use flake` in my `.envrc`. When I `cd` into the directory I get the following:

```
❯ cd ulidgen
direnv: loading ~/src/github.com/jamesottaway/ulidgen/.envrc
direnv: using flake
warning: Git tree '/Users/james/src/github.com/jamesottaway/ulidgen' is dirty
/nix/store/zqyb1i0phqpf2gkg7yna8v4i2p4c3zf4-nix-direnv-1.1/share/nix-direnv/direnvrc:69: realpath: command not found
ln: /Users/james/src/github.com/jamesottaway/ulidgen/.direnv/flake-profile: Invalid argument
direnv: renewed cache
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +LD_DYLD_PATH +MACOSX_DEPLOYMENT_TARGET +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_apple_darwin +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_apple_darwin +NIX_CFLAGS_COMPILE +NIX_COREFOUNDATION_RPATH +NIX_DONT_SET_RPATH +NIX_DONT_SET_RPATH_FOR_BUILD +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_IGNORE_LD_THROUGH_GCC +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_NO_SELF_RPATH +NIX_STORE +NM +NODE_PATH +PATH_LOCALE +RANLIB +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +__darwinAllowLocalNetworking +__impureHostDeps +__propagatedImpureHostDeps +__propagatedSandboxProfile +__sandboxProfile +buildInputs +builder +configureFlags +configurePhase +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +distPhase +doCheck +doDist +doInstallCheck +dontAddDisableDepTrack +gl_cv_func_getcwd_abort_bug +installPhase +name +nativeBuildInputs +node_modules +out +outputs +patches +pname +propagatedBuildInputs +propagatedNativeBuildInputs +shell +src +stdenv +strictDeps +system ~PATH
```

I do have `realpath`, however:

```
❯ which realpath
/nix/store/96yx22s06r1y7rcp1lyz25q8j1ymwmng-coreutils-8.32/bin/realpath
```

**Comment by Mic92** [comment]
Not quite sure why it is not found but would `readlink -f` work for you in this place? https://github.com/nix-community/nix-direnv/blob/9b3e62f10f0b1886ada0346fc922768384ec99fc/direnvrc#L71

**Comment by jamesottaway** [comment]
Yep, that'll work on macOS, but I guess it'll have to be conditional for *nix distros which are the other way around.

As for why, I'm not super familiar with the inner workings of direnv but it mustn't run an interactive shell and hence not load my Nix profile.

**Comment by Mic92** [comment]
No `readlink` also works on Linux.

**Comment by nathanshelly** [comment]
Hi I'm running into the same issue but failing to get the recommended suggestion to work successfully. I replaced the `drv=$(realpath "$tmp_profile")` with this:

```bash
    drv=$(readlink -f "$tmp_profile")
```

Unfortunately I then get the following error:

```shell
❯ touch .envrc
warning: Git tree '/Users/nathan/dev/locations' is dirty
readlink: illegal option -- f
usage: readlink [-n] [file ...]
ln: /Users/nathan/dev/locations/.direnv/flake-profile/.: Resource busy
ln: /nix/var/nix/gcroots/per-user/nathan/Users-nathan-dev-locations/flake-profile: Read-only file system
```

This makes sense to me since the version of readlink that ships with macOS (`/usr/local/bin/readlink`) has no `-f` option. Installing a version of `readlink` that does support `-f` didn't do anything which I wouldn't really expect it to. Am I misunderstanding the fix? Is there anything else I can do to solve this?

**Comment by Mic92** [comment]
> Hi I'm running into the same issue but failing to get the recommended suggestion to work successfully. I replaced the `drv=$(realpath "$tmp_profile")` with this:
> 
> ```shell
>     drv=$(readlink -f "$tmp_profile")
> ```
> 
> Unfortunately I then get the following error:
> 
> ```shell
> ❯ touch .envrc
> warning: Git tree '/Users/nathan/dev/locations' is dirty
> readlink: illegal option -- f
> usage: readlink [-n] [file ...]
> ln: /Users/nathan/dev/locations/.direnv/flake-profile/.: Resource busy
> ln: /nix/var/nix/gcroots/per-user/nathan/Users-nathan-dev-locations/flake-profile: Read-only file system
> ```
> 
> This makes sense to me since the version of readlink that ships with macOS (`/usr/local/bin/readlink`) has no `-f` option. Installing a version of `readlink` that does support `-f` didn't do anything which I wouldn't really expect it to. Am I misunderstanding the fix? Is there anything else I can do to solve this?

Maybe just `readlink` without `-f` is actually enough for this use case.

**Comment by nathanshelly** [comment]
🤦 didn't even think to try that. Worked perfectly, thanks!
