### ISSUE TITLE
Using direnv with flakes builds a recursive source tree

### ISSUE THREAD

**Issue by szlend** [nix-community/nix-direnv#67]
Every time you make a change that triggers a direnv rebuild, it generates a `.direnv/flake` symlink that points to the application source tree in the nix store `/nix/store/*-source/`. The problem is that after the first rebuild, it starts including this symlink in the nix store source directory itself. This keeps happening recursively until you have paths like `.direnv/flake/.direnv/flake/.direnv/flake` etc. This causes various text editors to explode unless you specifically configure it to ignore `.direnv`.

It's not a big issue and can be worked around easily in most editors, but I'm wondering if this could somehow be avoided in the first place.

**Comment by Mic92** [comment]
I wonder why .direnv/flake is part of the flake in the first place because it is not part of git.

**Comment by Mic92** [comment]
Turns out it was not doing the right thing: https://github.com/nix-community/nix-direnv/pull/68

**Comment by Mic92** [comment]
This is fixed now in #68
