### ISSUE TITLE
NIX_BIN_PREFIX: unbound variable

### ISSUE THREAD

**Issue by aaschmid** [nix-community/nix-direnv#70]
Since version 1.2.3 I get the following error 

```
~/work/some-dir
direnv: loading ~/work/some-dir/.envrc
direnv: using nix
/nix/store/4aifrh1mksd52aam92a4zc6hzjvargrk-nix-direnv-1.2.3/share/nix-direnv/direnvrc:145: NIX_BIN_PREFIX: unbound variable
```

It works with version 1.2.1.

My system info is 
```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.10`
 - channels(user): `"darwin, home-manager"`
 - channels(root): `"nixpkgs-21.05pre272202.7fd33568097, darwin, home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Which other information are required?

I haven't investigated further yet, but if you have a tip for me how to fix, I can also try to provide a PR

**Comment by Mic92** [comment]
This is set here: https://github.com/nix-community/nix-direnv/blob/04f80bf41711dcb2ae9b706fce2058386299ac7f/direnvrc#L4
Do you have by chance anything in your .envrc that unsets `NIX_BIN_PREFIX`?

**Comment by aaschmid** [comment]
I am not sure about your question. I use `use_nix()` and there `NIX_BIN_PREFEX` is set: https://github.com/nix-community/nix-direnv/blob/04f80bf41711dcb2ae9b706fce2058386299ac7f/direnvrc#L145.

Most of my `.envrc` files only have `use nix`. I tried with various `shell.nix` files using nodejs, java, python with virtual envs.

Does that help?

**Comment by Mic92** [comment]
> I am not sure about your question. I use `use_nix()` and there `NIX_BIN_PREFEX` is set:
> 
> https://github.com/nix-community/nix-direnv/blob/04f80bf41711dcb2ae9b706fce2058386299ac7f/direnvrc#L145
> .
> 
> Most of my `.envrc` files only have `use nix`. I tried with various `shell.nix` files using nodejs, java, python with virtual envs.
> 
> Does that help?

Can you put `set -x` in your ~/.direnvrc before nix-direnv is sourced?
I currently cannot reproduce what is going on in your case.

**Comment by aaschmid** [comment]
Here is the result of my first and in depth investigation:

1. My `direnvrc` installed via `home-manager` has following line to check for `$NIX_BIN_PREFIX`: `if [[ -z ${NIX_BIN_PREFIX:-/nix/store/q0z2kvkgrpvaipa87jl98qh7g5pym5fj-nix-2.3.10/bin/} ]]; then` 
2. Changing this to `if [[ -z ${NIX_BIN_PREFIX:-} ]]; then` and it works as expected
3. This change comes from `pkgs/tools/misc/nix-direnv/default.nix` line 18: `--replace "\''${NIX_BIN_PREFIX:-}" "\''${NIX_BIN_PREFIX:-${nix}/bin/}" \`
4. Creating an overlay with following fixes it:
  ```
     nixpkgs.overlays = [
      (self: super: {
        nix-direnv = super.nix-direnv.overrideAttrs (oldAttrs: rec {
          # Substitute instead of wrapping because the resulting file is getting sourced, not executed:
          postPatch = ''
            substituteInPlace direnvrc \
              --replace "grep" "${super.gnugrep}/bin/grep"
          '';
        });
      })
    ];
  ```
Sorry for not doing deep investigation earlier. If you aggree with that change I can create a PR for it on nixpkgs repo.

**Comment by aaschmid** [comment]
The other alternative might be changing 
```
--replace "\''${NIX_BIN_PREFIX:-}" "\''${NIX_BIN_PREFIX:-${nix}/bin/}" \
```
to
```
--replace "\''${NIX_BIN_PREFIX:}" "\''${NIX_BIN_PREFIX:-${nix}/bin/}" \
```
(Note the missing `-` in order to set a proper default for `$NIX_BIN_PREFIX` if there is a problem with setting it at the beginning ...

**Comment by Mic92** [comment]
> The other alternative might be changing
> 
> ```
> --replace "\''${NIX_BIN_PREFIX:-}" "\''${NIX_BIN_PREFIX:-${nix}/bin/}" \
> ```
> 
> to
> 
> ```
> --replace "\''${NIX_BIN_PREFIX}" "\''${NIX_BIN_PREFIX:-${nix}/bin/}" \
> ```
> 
> (Note the missing `:-` in order to set a proper default for `$NIX_BIN_PREFIX` if there is a problem with setting it at the beginning ...

yes please.

**Comment by aaschmid** [comment]
@Mic92: Should I also change the `nixFlakes` usage in the https://github.com/nix-community/nix-direnv/blob/aca3a321457ef6109b7afbca4faf32d6e35e239e/default.nix#L10 as we did in `nixpkgs`?

**Comment by Mic92** [comment]
> @Mic92: Should I also change the `nixFlakes` usage in the
> 
> https://github.com/nix-community/nix-direnv/blob/aca3a321457ef6109b7afbca4faf32d6e35e239e/default.nix#L10
> as we did in `nixpkgs`?

See https://github.com/NixOS/nixpkgs/pull/114622/files#r584597612
