### ISSUE TITLE
direnv export fish fails with buildFHSUserEnv

### ISSUE THREAD

**Issue by cideM** [nix-community/nix-direnv#72]
I have a `shell.nix` that unfortunately requires me to use `buildFHSUserEnv`. `nix shell` works, but `nix-direnv` doesn't.

```shell
$ touch shell.nix
direnv: loading ~/some_dir/.envrc
direnv: using nix
cypress-chrootenv:tifa@nixos:~/some_dir$ direnv: 
  ([/nix/store/4ikbx711q3ajvsw74m9sqzk02xcrk6cr-direnv-2.27.0/bin/direnv export fish]) 
  is taking a while to execute. Use CTRL-C to give up.
^C
cypress-chrootenv:tifa@nixos:~/some_diri$ exit

direnv: eval /home/tifa/some_dir/.direnv/cache-.3341.df8e3bd1109
direnv: export +IN_NIX_SHELL ~PATH
```

_I inserted the line breaks around the Nix store path manually so it's easier to read without scrolling_

It doesn't tell me anything else. It works in all other folders where I'm just using `mkShell`.

I'm on NixOS.

**Comment by Mic92** [comment]
Sorry. I cannot support this use case can you someone launch fish from `buildFHSUserEnv` instead?

**Comment by cideM** [comment]
Got it. It's already good to know that this is not a bug but just not a feature.

I expect `buildFHSUserEnv` to be a rarity. In this case I ended up creating a separate `foo_shell.nix` for just that one thing. Thanks for the quick reply!
