### ISSUE TITLE
XDG_DATA_DIRS not preserved in use_flake

### ISSUE THREAD

**Issue by ncfavier** [nix-community/nix-direnv#74]
20e2676b1998232bb4d1996e6431b2ee00cee30a removed `_nix_import_env` from `use_flake`, which means the fix in 7ac4290e8247e935fdab5830b2373e41427af237 doesn't apply to `use_flake`, which means `XDG_DATA_DIRS` isn't preserved, which means dynamic shell completion loading fails.

**Comment by Mic92** [comment]
cc @meck

**Comment by meck** [comment]
@ncfavier I dont use flake myself, if you  could try #75
