### ISSUE TITLE
nix-direnv doesn't seem to cache

### ISSUE THREAD

**Issue by MedeaMelana** [nix-community/nix-direnv#78]
Hello,

I believe I've followed all instructions at https://github.com/nix-community/nix-direnv/blob/master/README.md (Via `configuration.nix` in NixOS), and although nix-direnv is giving me correct results, it seems to want to re-evaluate my `shell.nix` every time I `cd` into the directory. Is there a way to debug what is causing it to not reuse a previous result? What settings should I check?

```
$ nixos-option nix.extraOptions
Value:
''
  keep-outputs = true
  keep-derivations = true
''

Default:
""
(...)

$ nixos-option environment.pathsToLink
Value:
[
  "/share/nix-direnv"
(...)
```

I do notice that `/share/nix-direnv` does not exist, is that a problem?

Thank you

**Comment by Mic92** [comment]
It should not create `/share/nix-direnv` but `/run/current-system/sw/share/nix-direnv`.
Check that you have the following file after nixos-rebuild switch: `/run/current-system/sw/share/nix-direnv/direnvrc`

**Comment by MedeaMelana** [comment]
Ah alright, yes that directory does exist, and I also have that file (it's a symlink).

**Comment by Mic92** [comment]
Ok. And you did source this file in your direnvrc?

**Comment by MedeaMelana** [comment]
I did not :-( I don't know how I missed that, I'm very sorry. Thanks for the help! Everything is working now.
