### ISSUE TITLE
nix-direnv generates a file named "-" when running direnv allow

### ISSUE THREAD

**Issue by cpcloud** [nix-community/nix-direnv#83]
It seems to be happening here https://github.com/nix-community/nix-direnv/blob/master/direnvrc#L202, though it's not entirely clear what the intent is/was with writing to `-`.

**Comment by Mic92** [comment]
I just noticed that I accidentally pushed a commit that was not supposed by in master as its experimental.
Revert in #85

**Comment by Mic92** [comment]
Fixed.
