### ISSUE TITLE
New direnvrc is constantly re-evaluating

### ISSUE THREAD

**Issue by duckpuppy** [nix-community/nix-direnv#84]
I've started seeing an issue when using this integration through home-manager. A recent change seems to have caused it to re-evaluate the cache constantly - upon entering a directory with an `.envrc` file containing `use nix`, I see the following every time the prompt is redrawn:

```
loading ~/<project-dir>/.envrc
renew cache in background
```

I see that along with any output my shell hook would show in my `shell.nix` - which for some of my projects is a LOT of output if it, say, builds a go environment or caches vendored dependencies.

**Comment by Mic92** [comment]
I just noticed that I accidentally pushed a commit that was not supposed by in master as its experimental.
Revert in https://github.com/nix-community/nix-direnv/pull/85

**Comment by Mic92** [comment]
Fixed.
