### ISSUE TITLE
--extra-experimental-features check passes when it is not allowed

### ISSUE THREAD

**Issue by lrworth** [nix-community/nix-direnv#89]
After updating to nixos-21.05 and nix 2.3.11, running `direnv reload` issues this warning:

```
warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user
```

`nix-direnv` uses this test to check that experimental features can be enabled:
```bash
  if "${NIX_BIN_PREFIX}nix-shell" --extra-experimental-features '' --version 2>/dev/null >&2; then
    experimental_flags+=('--extra-experimental-features' 'nix-command flakes')
  fi
```

It appears that this test does not work:
```console
$ NIX_BIN_PREFIX=/nix/store/nbr38zzkkypjxnq3l7w0d9wscxxwv00x-nix-2.4pre20210503_6d2553a/bin/
$ "${NIX_BIN_PREFIX}nix-shell" --extra-experimental-features '' --version
nix-shell (Nix) 2.4pre20210503_6d2553a
$ echo $?
0
$ "${NIX_BIN_PREFIX}nix-shell" --extra-experimental-features ''
warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user
...
```

**Comment by Mic92** [comment]
The check was meant to detect if the current nix supports the experimental flag.
I was not aware that the experimental flag does not work for not trusted users.
I don't see a way of enabling the nix-command than because this is needed for nix-direnv.
One could only improve the error message slightly on how to configure the system to have `experimental-features` enabled.

**Comment by Mic92** [comment]
So to solve this issue: Either enable experimental flags globally or make your user a trusted user.

**Comment by lrworth** [comment]
Alternatively, it could guard against this particular scenario in addition to the existing test? This command is fast and appears to work:

```
nix-build --extra-experimental-features '' -E 2>&1 | grep "warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user" >/dev/null
```

**Comment by lrworth** [comment]
FWIW I attempted adding this check and then encountered another warning due to use of the `nix` command, which requires the `nix-command` feature. Considering `use_nix()` doesn't work without experimental flags, perhaps the test could be removed altogether, and a hard requirement on experimental flags added.

**Comment by Mic92** [comment]
It needs experimental flags but if users are trusted users they can be enabled. Also nix-direnv can use a pre-installed nix instead of a bundled one depending on how it is installed. So it could be the case that it is installed with the stable version of nix.

**Comment by lrworth** [comment]
None of these solutions are very appealing. I don't want my user to be a trusted user, and adding a global `experimental-features` setting causes warnings from stable nix. I'll put up with it until https://github.com/NixOS/nix/issues/4882 is resolved.

**Comment by lrworth** [comment]
Adding this nixpkgs overlay fixes the warning for me (and probably stops flakes from working — I don't use them so I don't know):
```nix
self: super: with self; { nix-direnv = super.nix-direnv.override { nixUnstable = self.nix; }; }
```

Could be worth making that the default in nixpkgs, and/or configurable with a flag.
