### ISSUE TITLE
Explanation how it compares with lorri

### ISSUE THREAD

**Issue by takeda** [nix-community/nix-direnv#9]
Unless I'm wrong, I believe this overlaps with lorri project (from target) how does it compare? What are its strengths? Lorri requires to have a deamon running, looks like this doesn't at first that seems like advantage. Is it possible to add something in the readme that would explain why one would want to use this project?

**Comment by Mic92** [comment]
Lorri is unusable for people that have NIXPKGS to something else but a channel (i.e. a git repository) as it tries to revaluate all nix sources every time something changes. This leads to high CPU usage.
