### ISSUE TITLE
shellHook caching inconsistency with and without flakes

### ISSUE THREAD

**Issue by ryneeverett** [nix-community/nix-direnv#90]
In cached shells, the shellHook does not execute with `use nix` but does with `use flake`.

It would be easy to achieve consistency by piping the `nix print-dev-env` output through `sed` to remove the final `eval "$shellHook"`, but I'm not sure this is the right direction. It seems that `nix develop` runs the shellHook even when cached so perhaps it's better not to fight the pattern flakes is currently implementing.

I'm not sure if this is a bug or just a (documentation-worthy?) distinction but it does complicate the creation of environments compatible with or without flakes. For example, I was planning to use an .envrc like:

```
nix flake --help > /dev/null \
  && use flake \
  || use nix
```

but heavy shellHooks will need to be rewritten to check whether their expensive processes have been run already.

**Comment by Mic92** [comment]
Do you have in your project both a flake.nix and a shell.nix?

**Comment by ryneeverett** [comment]
Yes, `devShell` is set to the imported shell.nix. I should have time to upload a demo project this weekend if that would be helpful.

**Comment by ryneeverett** [comment]
Demo: https://gitlab.com/ryneeverett/nix-direnv-shellhook-demo

**Comment by Mic92** [comment]
Ok. I would accept patches to fix this. Ideally with a test.

**Comment by ryneeverett** [comment]
I just pushed another README section to the demo demonstrating that while `nix develop` caches the nix evalutation, the shellHook still gets run on cached invocations.

However having taken a second look this inconsistency doesn't bother me. Caching is more of a feature of the new nix cli than the develop subcommand specifically and `nix develop` seems more like an improved `nix-shell` than a competitor with third party development environment caching tools like nix-direnv and lorri.
