### ISSUE TITLE
nixpkgs made flakes support optional; breaks things

### ISSUE THREAD

**Issue by patr-ck** [nix-community/nix-direnv#92]
https://github.com/NixOS/nixpkgs/commit/03310df843a344215b45b2e8aef11ae9402a40e2

That commit has made flakes support optional for nix-direnv in nixpkgs, and now the home-manager installation method (and probably the others as well) does not work.  Using a flake based envrc gives errors.

**Comment by Mic92** [comment]
This needs to be fixed in home-manager than by adding a flake option. Or it can be overridden with an overlay/packagesOverrides.

**Comment by happysalada** [comment]
There is a PR open for that in home-manager btw https://github.com/nix-community/home-manager/pull/2089

**Comment by happysalada** [comment]
@Mic92 not really sure where the best place to post this is. Would you mind adding another github support tier at 10$ ?

**Comment by Mic92** [comment]
@happysalada done thanks!

**Comment by thomasbach-dev** [comment]
This one seems to work:
``` nix
  nixpkgs.overlays = [
    (self: super: { nix-direnv = super.nix-direnv.override { enableFlakes = true; }; } )
  ];
```
