### ISSUE TITLE
Additional documentation wrt attributes

### ISSUE THREAD

**Issue by rmanne** [nix-community/nix-direnv#94]
It looks like this package supports attributes with something like `use nix -A shells.ghc`. This is really nice to have, but I think this would be nice to have documented. (Additional nix flags might also be useful to be documented.)

**Comment by Mic92** [comment]
Some bits are documented here: https://direnv.net/man/direnv-stdlib.1.html#codeuse-nix-code
And also here: https://github.com/nix-community/nix-direnv#flakes-support

**Comment by Mic92** [comment]
I personally did not thought about using `-A` yet but it sounds like interesting idea. There are also no tests yet for flags like that so it might be better to have them tested first before documenting them.

**Comment by Mic92** [comment]
Let's leave this undocumented until we have tests.
