### ISSUE TITLE
Cannot install via home-manager

### ISSUE THREAD

**Issue by Mdsp9070** [nix-community/nix-direnv#96]
I tried to add as README says:

```nix
programs = {
    direnv = {
      enable = true;
      nix-direnv.enable = true;
    };
  };
```

However I always get this error: 
```sh
error: The option `programs.direnv.nix-direnv' does not exist. Definition values:
- In `/home/matthew/documents/privy/dotfiles/home/home.nix':
    {
      enable = true;
    }
(use '--show-trace' to show detailed location information)

There are 158 unread and relevant news items.
Read them by running the command 'home-manager news'.
```

***Metadata***
 - system: `"x86_64-linux"`
 - host os: `Linux 5.12.9, NixOS, 21.11pre295280.fa0326ce523 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.12`
 - channels(root): `"nixos-21.11pre295280.fa0326ce523"`
 - channels(matthew): `"home-manager, nixos-21.05pre289339.83d907fd760, nixpkgs-21.05pre289536.c58b97674b1"`
 - nixpkgs: `/home/matthew/.nix-defexpr/channels/nixpkgs`

**Comment by Mic92** [comment]
I think your home-manager is older: https://github.com/nix-community/home-manager/pull/2089
The option was called `enableNixDirenvIntegration` before.

**Comment by Mdsp9070** [comment]
Correct! I'm not used to upadte channels yet haha! Thanks for noting it!
